### ISSUE TITLE
Parkposition und Datum (VwConnectGo) 

### ISSUE THREAD

**Issue by Hini2001** [TA2k/ioBroker.vw-connect#10]
Hallo. 
Erst einmal danke für den coolen Adapter.

Ich habe einen VW dataplug und die we connect go app auf meinem Handy. 

Ich habe den Adapter installiert und alles eingetragen. Es werden auch Daten an den Broker übermittelt. 
Aber die Park Positions Daten sind nicht aktuell (obwohl sie in der App korrekt dargestellt werden). 
Außerdem habe ich bei den Datums Anzeigen eine sehr lange Zahl, welche ich nicht deuten kann. 

Ist es bei Benutzung des Dataplugs und de connect go app NICHT möglich die zeit/km bis zur inspektion/ölwechsel auszulesen? Ich habe diese datenpunkte nicht gefunden. 

Ansonsten ist der Adapter schon recht geil. 

Vielen Dank dafür und auch für die schnelle Hilfe.

**Comment by TA2k** [comment]
Manche Daten werde nur auf dem smartphone gespeichert aber nicht an den VW Server gesendet wo der Adapter sie auslesen kann. Das kannst du testen wenn du die app löscht und neuinstallierst dann siehst du ja welche daten da sind ohne das du dich mit dem auto verbunden hast. die lange zahl ist wahrscheinlich ein timestamp

**Comment by Hini2001** [comment]
Hallo.
Alles klar. Das mit dem Timestamp hab ich hinbekommen. 

Ich weiß das die parkposition ebenfalls online gesichert wird. Sonst würde er mir ja keine parkposition anzeigen. Allerdings nimmt er eine von letzter Woche. Und das wundert mich. Diese aber sehr genau.

**Comment by Hini2001** [comment]
Die parkposition stimmt leider immer noch nicht. Im Broker sind immer noch alte Daten hinterlegt. Und bei jeder Aktualisierung werden auch wieder diese Daten eingelesen. Während in der connect go app die "fast" korrekte parkposition hinterlegt ist.

**Comment by Hini2001** [comment]
Ich habe jetzt noch ein weiteres Mal die App deinstalliert und wieder installiert. Aber leider habe ich immer noch eine "veraltete" Parkposition angezeigt.
Woran kann das liegen? Und was kann ich noch tun, um die "aktuelle" und App gleiche Parkposition im Iobroker angezeigt zu bekommen?

**Comment by TA2k** [comment]
Meinst du mit App die vw App?  Nutzt du den bzw odb Adapter odeR hat dein vw des direkt integriert

**Comment by Hini2001** [comment]
Hey. So wie oben beschrieben.
Die we connect go app und den vw dataplug.
Leider eine Auto Bj 2015.

**Comment by Hini2001** [comment]
Hmm... Jetzt mehrere Tage getestet und immer noch die selber im iobroker eingetragene Parkposition. 
Hast du eventuell ne Idee woran das liegen kann?

**Comment by TA2k** [comment]
Tut mir ich habe selber keine odb adapter und kann es nicht testen ob vw vielleicht was geändert hat.
