### ISSUE TITLE
cruisingRangeElectric_km may return 0x3FFF in ID API

### ISSUE THREAD

**Issue by tillsteinbach** [TA2k/ioBroker.vw-connect#103]
**Describe the bug**  
The ID API may respond for cruisingRangeElectric_km with 16383 which is 0x3FFF or 0b11111111111111 and looks pretty much like an errorstate. Also the VW Connect App shows only dashes at the same time

**To Reproduce**  
Hard to reproduce. Don't know yet when this happens

**Expected behavior**  
Also hard to say. Maybe setting the State to something like NaN to indicate the error?

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/3825852/118122501-3c98be00-b3f3-11eb-9ee4-eee7d8d025ec.png)

**Versions:**  
 - Adapter version: 0.0.33

**Comment by TA2k** [comment]
Problem with the app I dont think I can fix this
