### ISSUE TITLE
Adapter does not start after updating js-controller to version 3.017

### ISSUE THREAD

**Issue by egbertgertz** [TA2k/ioBroker.vw-connect#11]
**Describe the bug**  
I have updated the js-controller to 3.017. After restart iobroker, vw-connect won't to go activ. After activating it goes a shortly to "green" and then it will be "red".
In the log of iobroker came many failure messages:

vw-connect.0 | 2020-04-23 23:47:10.358 | error | at process._tickCallback (internal/process/next_tick.js:69:34)
-- | -- | -- | --
vw-connect.0 | 2020-04-23 23:47:10.358 | error | at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
vw-connect.0 | 2020-04-23 23:47:10.358 | error | at process.emit (events.js:198:13)
vw-connect.0 | 2020-04-23 23:47:10.358 | error | at process.exceptionHandler (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8239:73)
vw-connect.0 | 2020-04-23 23:47:10.358 | error | (23678) TypeError: Cannot read property 'message' of undefined
vw-connect.0 | 2020-04-23 23:47:10.357 | error | (23678) uncaught exception: Cannot read property 'message' of undefined
vw-connect.0 | 2020-04-23 23:47:10.356 | error | (23678) 406

Please, can you check this issue. Thank you very much.

**Comment by Rangerope** [comment]
I get exactly the same behavior, running on Mac OS with  node.js v12.16.3.

**Comment by TA2k** [comment]
install vw connect from github and try again or try to install js-controller 3.0.21 from github

**Comment by Rangerope** [comment]
Reinstalling the vw-connect adapter from GitHub worked for me. Thanks, TA2k. Great show.
