### ISSUE TITLE
login fails

### ISSUE THREAD

**Issue by GoClyde** [TA2k/ioBroker.vw-connect#119]
**Describe the bug**  
Login attempt results in error.
Didn't change anything. Error occurs consistantly since 3 days ago.
Type: VW (same problem with VWv2)

**Screenshots & Logfiles**  

vw-connect.0 | 2021-06-11 15:00:58.414 | error | (30204) Login Failed
-- | -- | -- | --
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at IncomingMessage.emit (events.js:326:22)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Object.onceWrapper (events.js:420:28)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at IncomingMessage.&lt;anonymous&gt; (/opt/iobroker/node_modules/request/request.js:1076:12)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request.EventEmitter.emit (domain.js:483:12)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request.emit (events.js:314:20)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request.&lt;anonymous&gt; (/opt/iobroker/node_modules/request/request.js:1154:10)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request.EventEmitter.emit (domain.js:483:12)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request.emit (events.js:314:20)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.vw-connect/main.js:469:105)
vw-connect.0 | 2021-06-11 15:00:58.412 | error | (30204) TypeError: Cannot read property 'split' of undefined
vw-connect.0 | 2021-06-11 15:00:58.391 | error | (30204) TypeError: Cannot read property 'split' of undefined
vw-connect.0 | 2021-06-11 15:00:58.390 | error | (30204) Login was not successful, please check your login credentials and selected type
vw-connect.0 | 2021-06-11 15:00:56.271 | info | (30204) starting. Version 0.0.30 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v12.20.2, js-controller: 3.1.6

**Comment by nightsha-de** [comment]
You need to accept the updated TOU on the website and/or in the WeConnect app.

**Comment by TA2k** [comment]
Or install via github the version will try to auto accept
