### ISSUE TITLE
Login Failed -Seat Mii

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.vw-connect#120]
Seit gestern loggt sich der Adapter bei SEAT nicht mehr ein. Es erscheint folgende Fehlermeldung:

vw-connect.0 | 2021-06-14 08:31:47.915 | error | (14908) Login Failed
vw-connect.0 | 2021-06-14 08:31:47.903 | error | (14908) TypeError: body.matchAll is not a function

Ein einloggen in der Android App ist möglich.

Fehler tritt auf in Version 0.0.34

ich bin dann einiger Versionen zurück, 0.0.30 ließ sich downgraden und hier funktioniert der Login.

**Comment by TA2k** [comment]
Ich habe dir via iobroker forum geschrieben

**Comment by TA2k** [comment]
I see i use a node 12 method

**Comment by TA2k** [comment]
add v10 compatibility in 0.0.35
