### ISSUE TITLE
Set updateInterval from outside / via script

### ISSUE THREAD

**Issue by randomname32** [TA2k/ioBroker.vw-connect#123]
Hi,
I would like to change the update interval dynamically. Usually one update per day is sufficient, but when I have the wallbox-charger plugged in, I would like to get an update every let's say 10 minutes, to see how the battery gets filled up. After the battery is full, there's no need to keep updating, because nothing will change anymore.

Can I set the update-interval setting of this adapter programmatically?

**Comment by TA2k** [comment]
The communication will only receive changed data. No reason to optimize this

**Comment by randomname32** [comment]
My goal was not to get only changed data. My goal was to reduce the number of calls to the VW servers.
Or is it not necessary to reduce them? The ioBroker instance help text says to not update more often than every 6 hours. "
Status Update erzwingen. (Interval in Minuten, 0 = Aus). Anzahl Updates zwischen Zündungen ist limitiert, unter 360min nicht zu empfehlen!
" 
I would like to update every 10minutes during a charging session and when charging finished stop updating. Does that make sense? Maybe I misunderstood something.
