### ISSUE TITLE
invalid trip type

### ISSUE THREAD

**Issue by Maverick78de** [TA2k/ioBroker.vw-connect#14]
I have disabled the download of trip information in setup.
Now I get this error on every poll

Version 0.0.12

`

vw-connect.0 | 2020-05-10 16:04:19.836 | error | (2098) {"error":{"errorCode":"gw.error.parameter","description":"Invalid Trip Type"}}
-- | -- | -- | --
vw-connect.0 | 2020-05-10 16:04:19.835 | error | (2098) 400
vw-connect.0 | 2020-05-10 16:04:19.830 | error | (2098) {"error":{"errorCode":"gw.error.parameter","description":"Invalid Trip Type"}}
vw-connect.0 | 2020-05-10 16:04:19.827 | error | (2098) 400

`

**Comment by TA2k** [comment]
should be fixed in v 0.0.13
