### ISSUE TITLE
dosen't connect - error "No Token received."

### ISSUE THREAD

**Issue by radebold** [TA2k/ioBroker.vw-connect#141]
Hi together,

I installed this adapter and try to run, but it dosen't work.

logfiles show
`No Token received.
No Token received visiting url and accept the permissions.
`

What can I do ?

Thx
Thomas

**Comment by TA2k** [comment]
Did you choose the correct type and relogin via app and accept all notifications?

**Comment by radebold** [comment]
ok, my mistake I have selected VW, don't see the GO item.
Now it is connected and all fine :-)
