### ISSUE TITLE
Password reset from VW due to high amount of requests

### ISSUE THREAD

**Issue by para2573** [TA2k/ioBroker.vw-connect#146]
Hi there,

I just got an email from VW ID Support - no junk or spam mail - that my password was resented due to a massive amount of requests.
I only installed the iobroker tool 4 weeks ago but haven’t used it for any purpose. This is only a question if it could possibly the case that there is a connection to this?
BR
Michael

**Comment by TA2k** [comment]
What is your refresh interval ? It could be did you see any errors in the ioBroker log?
Maybe you can ask them what they mean with amount of requests

**Comment by para2573** [comment]
It was as in standard value 15 minutes. I ask them…

**Comment by TA2k** [comment]
Did you use type vwV2?

**Comment by para2573** [comment]
Si senior

**Comment by TA2k** [comment]
This means you have in the past som error regarding refresh token this leads to a relogin every hour. Maybe this is a reason for the mail

**Comment by TA2k** [comment]
Reset of the password and update to 0.0.41 should solve the issue
