### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by amnesia106** [TA2k/ioBroker.vw-connect#147]
Vw-connect is updated to 0.0.41 - but I can’t login to my vw since 14 September evening.
```
vw-connect.0 | 2021-09-15 16:50:47.272 | error | Login Failed
-- | -- | -- | --
vw-connect.0 | 2021-09-15 16:50:47.271 | error | Error: error=login.error.throttle
```

**Comment by TA2k** [comment]
Can you give Details about the car and your refresh interval or other errors in the log

**Comment by amnesia106** [comment]
VW eGolf - interval is 5 mins. 
debug says:

`{"date":"Wed, 15 Sep 2021 15:34:12 GMT","content-length":"0","connection":"close","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-language":"en-US","expires":"0","location":"/signin-service/v1/9496332b-ea03-4091-a224-8c746b885068@apps_vw-dilab_com/login/authenticate?relayState=75dafdc5a3fbcda92bea48d3683d00f4646ca7ee&email=XXX&nextButtonDisabled=true&enableNextButtonAfterSeconds=28&error=login.error.throttled","pragma":"no-cache","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-content-type-options":"nosniff","x-frame-options":"DENY","x-vcap-request-id":"462e95ed-f65f-4416-4aa7-685ee81bcbe9","x-xss-protection":"1; mode=block"}`

i have my email replaced with xxx

**Comment by TA2k** [comment]
Can you login via App but not other errors in the log

**Comment by amnesia106** [comment]
![4F4FFD22-88CC-4E43-8986-F92643FE5973](https://user-images.githubusercontent.com/40226796/133484546-a31f29ef-6cee-4db2-9611-9263c08bac37.jpeg)

#146

**Comment by amnesia106** [comment]
ive change my password and now all looks fine... it was probably a VW issue

**Comment by TA2k** [comment]
Which version u are using of the adapter which type u are using?

**Comment by TA2k** [comment]
Please update to 0.0.41
