### ISSUE TITLE
Token Error / Invalid protocol skodaconnect

### ISSUE THREAD

**Issue by gitknd** [TA2k/ioBroker.vw-connect#148]
Since a view days i've get Token errors (some information are masked by me). It's a Skoda Superb. Login with the app or by web is possible without errors:

<html>
<body>

vw-connect.0 | 2021-09-16 06:53:22.293 | debug | "{\"message\":\"Request method 'POST' not supported\"}"
-- | -- | -- | --
vw-connect.0 | 2021-09-16 06:53:22.292 | error | No Token received. Please try to login in via app or type VWv2 in the settings
vw-connect.0 | 2021-09-16 06:53:22.127 | debug | No Token received visiting url and accept the permissions.
vw-connect.0 | 2021-09-16 06:53:22.126 | debug | {"message":"internal error"}
vw-connect.0 | 2021-09-16 06:53:17.759 | debug | {"date":"Thu, 16 Sep 2021 04:53:17 GMT","content-length":"0","connection":"close","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-language":"en-US","expires":"0","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=*MASKED*&relayState=*MASKED*","pragma":"no-cache","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-content-type-options":"nosniff","x-frame-options":"DENY","x-vcap-request-id":"*MASKED*","x-xss-protection":"1; mode=block"}
vw-connect.0 | 2021-09-16 06:53:17.758 | debug | ""
vw-connect.0 | 2021-09-16 06:53:16.304 | debug | credentialsForm
vw-connect.0 | 2021-09-16 06:53:15.934 | debug | parseEmailForm
vw-connect.0 | 2021-09-16 06:53:12.812 | info | starting. Version 0.0.41 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v12.22.5, js-controller: 3.3.18
vw-connect.0 | 2021-09-16 06:53:12.802 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
vw-connect.0 | 2021-09-16 06:53:12.796 | debug | Plugin sentry Initialize Plugin (enabled=true)

</body>
</html>

<html>
<body>

Error from V 0.4 (i just downgraded for a test)

vw-connect.0 | 2021-09-16 07:02:36.036 | error | Login Failed
-- | -- | -- | --
vw-connect.0 | 2021-09-16 07:02:36.036 | error | "404 Not Found: Requested route ('tokenrefreshservice.apps.emea.vwapps.io') does not exist.\n"
vw-connect.0 | 2021-09-16 07:02:36.035 | error | 404
vw-connect.0 | 2021-09-16 07:02:36.034 | error | Failed to get token
vw-connect.0 | 2021-09-16 07:02:35.871 | debug | Error: Invalid protocol: skodaconnect:

</body>
</html>

**Comment by TA2k** [comment]
Skoda has login issue retry tomorrow

**Comment by gitknd** [comment]
login works now, but i still get:

<html>
<body>


vw-connect.0 | 2021-09-16 18:27:45.431 | error | Get Vehicles Failed
-- | -- | -- | --
vw-connect.0 | 2021-09-16 18:27:45.430 | info | No Vehicles found
vw-connect.0 | 2021-09-16 18:27:45.430 | debug | {"error":{"errorCode":"gw.error.authentication","description":"Malformed request"}}
vw-connect.0 | 2021-09-16 18:27:45.429 | error | 400
vw-connect.0 | 2021-09-16 18:27:45.265 | info | State value to set for "vw-connect.0.personal.emailAddresses" has to be one of type "string", "number", "boolean" but received type "object"



vw-connect.0 | 2021-09-16 18:27:44.930 | debug | getData
vw-connect.0 | 2021-09-16 18:27:44.929 | debug | Login successful
vw-connect.0 | 2021-09-16 18:27:44.928 | error | "<!doctype html><html lang=\"en\"><head><title>HTTP Status 403 – Forbidden</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> Access Denied</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class=\"line\" /><h3>Apache Tomcat</h3></body></html>"
vw-connect.0 | 2021-09-16 18:27:44.927 | error | 403
vw-connect.0 | 2021-09-16 18:27:44.927 | error | Failed to get VWToken
vw-connect.0 | 2021-09-16 18:27:44.521 | debug | Error: Invalid protocol: skodaconnect:


</body>
</html>

**Comment by TA2k** [comment]
fixed with 0.0.42
