### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by MiRen76** [TA2k/ioBroker.vw-connect#149]
Since the last few day I get an error on login:
2021-09-16 07:20:29.076 - error: vw-connect.0 (23763) Error: error=login.error.throttle

My configuration is as follows:
Node.js:v12.22.6
NPM:6.14.15
Adapter Version 0.0.39

**Comment by dervitti** [comment]
Same here with Adapter 0.0.39
```
vw-connect.1 | 2021-09-16 11:14:55.925 | error | "502 Bad Gateway: Registered endpoint failed to handle the request.\n"
vw-connect.1 | 2021-09-16 11:14:55.925 | error | 502
vw-connect.1 | 2021-09-16 11:14:55.924 | error | Failed to get token
vw-connect.1 | 2021-09-16 11:13:52.306 | error | Failed relogin
vw-connect.1 | 2021-09-16 11:13:52.306 | error | "502 Bad Gateway: Registered endpoint failed to handle the request.\n"
vw-connect.1 | 2021-09-16 11:13:52.306 | error | 502
vw-connect.1 | 2021-09-16 11:13:52.305 | error | Failed to get token
vw-connect.1 | 2021-09-16 11:13:46.931 | error | Relogin
vw-connect.1 | 2021-09-16 11:13:21.828 | error | Relogin
vw-connect.1 | 2021-09-16 11:13:14.911 | error | "502 Bad Gateway: Registered endpoint failed to handle the request.\n"
vw-connect.1 | 2021-09-16 11:13:14.911 | error | 502
vw-connect.1 | 2021-09-16 11:13:14.911 | error | Failed relogin
```

**Comment by TA2k** [comment]
@MiRen76 Please update on 0.0.41
@dervitti You are using skoda? Please wait until the 500error are gone

**Comment by nheuk** [comment]
i get some emails from vw and tronity.io. It seems that the interface has been disabled at the moment...

***************************** vw
Guten Tag xxx,

wir haben im Rahmen der Analyse einer ungewöhnlich hohen Last in einem der Systeme der mobilen Online-Dienste festgestellt, dass hierfür Anfragen verantwortlich sind, die im Zusammenhang mit Ihrem Benutzerkonto für die mobilen Online-Dienste We Connect stehen.

Aus diesem Grund war es notwendig Ihr Passwort zurückzusetzen, damit möglicher Schaden von Ihrem Fahrzeug und den Systemen abgewendet wird.

Nachdem wir Ihr Passwort zurückgesetzt haben, erhalten Sie eine E-Mail, die Sie zusätzlich über das Zurücksetzen des Passworts informiert.

In dieser E-Mail können Sie auf den blau hinterlegten „Passwort vergessen“ - Link klicken, um sich ein neues Passwort für Ihr Benutzerkonto anzulegen.

Wir entschuldigen uns für die Unannehmlichkeiten.

Sollten Sie weitere Fragen rund um unsere digitalen Dienste haben, stehen Ihnen unsere Mitarbeiter jederzeit unter der kostenfreien Rufnummer 0800 40 888 00 zur Verfügung. Unterstützt Ihr Telefonprovider diese Nummer nicht, rufen Sie bitte die
+49 5363 9223300 an. Die Kosten richten sich nach dem jeweiligen Tarif Ihres Anbieters. Bei Anrufen aus dem Ausland können Roaming-Gebühren anfallen.

Bitte nennen Sie bei Ihrem Anruf die Vorgangsnummer 920011, damit wir Ihnen schnellstmöglich weiterhelfen können.

Wir wünschen Ihnen allzeit eine sichere Fahrt mit Ihrem Volkswagen Golf.


Mit freundlichen Grüßen
Ihr Digital Service Team	 

**************************** tronity.io

Hallo xxx,

aktuell ist der Datenabruf Deiner Fahrzeugdaten (Hersteller: VW) leider pausiert. Wir arbeiten an der Lösungsfindung, können aber noch nicht abschätzen, wann wir den Datenabruf wieder aktivieren können.

Das tut uns sehr leid und wir bitten das zu entschuldigen! Wenn gewünscht, kannst Du in der Zwischenzeit Fahrten und Ladungen manuell erfassen:

**Comment by TA2k** [comment]
Should be fixed with 0.0.42 reset your password and your account should work fine again

**Comment by dervitti** [comment]
Great, thank you very much! Works perfectly again.
