### ISSUE TITLE
Nach Update Adapter bleibt gelb

### ISSUE THREAD

**Issue by steviec1211** [TA2k/ioBroker.vw-connect#15]
Hallo,

Bisher lief bei mir Version 0.0.13 mit dem js controller v3.0.19 zuverlässig.
Ich habe 2 Instanzen, einmal für Audi und einmal für Skoda.

Seit dem Update auf js controller 3.1.4 und we connect Adapter auf 0.0.15 wird der Adapter für Skoda Connect nur noch gelb. Für Audi funktioniert es wie gehabt. 

ich habe schon versucht auf 0.0.13 zurück zu gehen, aber gleiches Ergebnis

Mit freundlichen Grüßen
Steffen

**Comment by TA2k** [comment]
Ist das Problem dauerhaft welche Fehler zeigt der Log?

**Comment by steviec1211** [comment]
Hallo,

Momentan ist es so, das der Skoda Connect Dienst auch nicht funktioniert. Daher gehe ich davon aus das es nichts mit dem Adapter zu tun hat. Sobald der Connect Dienst wieder funktioniert, teste ich das noch aus und gebe dann Bescheid.

**Comment by THEIDEACOMPANY** [comment]
Bitte schaue mal hier. https://github.com/TA2k/ioBroker.vw-connect/issues/22
