### ISSUE TITLE
Status update failed

### ISSUE THREAD

**Issue by sprottasier** [TA2k/ioBroker.vw-connect#16]
Hallo,

vielen Dank für die Programmierung des Adapters. Ich nutze ihn seit gestern und bekomme im Log regelmäßig folgende Codes:

vw-connect.0 | 2020-06-02 20:23:10.332 | error | (12220) status update Failed
vw-connect.0 | 2020-06-02 20:23:10.332 | error | (12220) 429
vw-connect.0 | 2020-06-02 20:23:09.911 | error | (12220) status update Failed
vw-connect.0 | 2020-06-02 20:23:09.909 | error | (12220) 502

Ich kann einzelne Daten in den Objekten auslesen, die Fehlermeldung erscheint allerdings immer wieder. Ich habe bereits auf der VW HP das Gerät einmal abgemeldet und dann mich im ioBroker erneut angemeldet. Der Fehler bleibt bestehen.

**Comment by jens-maus** [comment]
FYI: Here I get similar error messages:

```
vw-connect.0 | 2020-06-11 17:56:38.811 | error | (23592) status update Failed
vw-connect.0 | 2020-06-11 17:56:38.811 | error | (23592) 502
```

**Comment by jensbocklage** [comment]
Same here...

vw-connect.0 | 2020-06-15 13:32:06.458 | error | (28006) status update Failed
-- | -- | -- | --
vw-connect.0 | 2020-06-15 13:32:06.456 | error | (28006) 502


btw.: nice to meet you here, jens-maus ;) Intensively using the carddav2fb script ;)

**Comment by TA2k** [comment]
kommt der fehler stabil über mehrere tage?

**Comment by Dirkn1** [comment]
Hallo,

ich bekomme eine Verbindung, dann aber Fehler ...  :-(

Dirk

![vw](https://user-images.githubusercontent.com/66989126/84736752-d5864580-afa6-11ea-855a-d3d07ebb8480.png)

**Comment by jensbocklage** [comment]
Ist bei mir ähnlich. Seit der Installation vor 2 Tagen.
![grafik](https://user-images.githubusercontent.com/7291642/84868043-5a8f5e80-b07c-11ea-977f-9fcaef88a140.png)

**Comment by heymkeyu** [comment]
Ich hatte mit der aktuell installierten Instanz keine neuen Daten mehr bekommen. 
Adapter deinstalliert, neu mit korrekten Daten eingerichtet.

Neue Instanz wird nur zum Teil mit Daten befüllt. 
Fehler im Log: 

vw-connect.0 | 2020-09-20 20:38:32.354 | error | (5475) status update Failed
vw-connect.0 | 2020-09-20 20:38:32.298 | error | (5475) 429

Unter der Seriennummer/Fahrgestellnummer(?) erhalte ich remote, rights. 

Unter der Instanz-Root einen 
leeren info-Knoten.
befüllten personal-Knoten

**Comment by Ricox1975** [comment]
schliesse mich an
selber Fehler

![image](https://user-images.githubusercontent.com/52467622/94153325-edf6dd80-fe7c-11ea-99b6-a120c7a2bbe7.png)

**Comment by Ricox1975** [comment]
Gibt's hier schon einen Ansatz?

**Comment by Dirkn1** [comment]
ich habe den Fehler immer noch  :-(  

Dirk

**Comment by TA2k** [comment]
Bitte mal die letzte version via github installieren und den fehler hier posten

**Comment by Dirkn1** [comment]
brauche ich eventuell eine bestimmte Version vom DataPlug?

hier hat sich seit der ersten Installation nichts mehr geändert:

![image](https://user-images.githubusercontent.com/66989126/104278982-ccf8dd80-54a9-11eb-8a6c-8a09b985596b.png)


 Fehlerliste:


![image](https://user-images.githubusercontent.com/66989126/104277424-1ac01680-54a7-11eb-9f3f-09f1ab58259f.png)


Dirk

**Comment by TA2k** [comment]
Ich bräuchte ein Zugang zu einem Go FAhrzeug um das zu beheben

**Comment by Dirkn1** [comment]
Hallo,

 

welchen Zugang?

 

Mein Admin, oder reicht Mitbenutzer?

 

Dafür brauche ich deine E-Mail – Adresse

 

Dirk

 

Von: TA2k [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. Januar 2021 08:51
An: TA2k/ioBroker.vw-connect
Cc: Dirkn1; Comment
Betreff: Re: [TA2k/ioBroker.vw-connect] Status update failed (#16)

 

Ich bräuchte ein Zugang zu einem Go FAhrzeug um das zu beheben

**Comment by TA2k** [comment]
Mitbenutzer reich einfach tombox im iobroker forum anschreiben

**Comment by oswi82** [comment]
Hi. I have the same issues since a couple of days. I am using version 0.0.23. Until 16th of January was running stable. I have a VW e-up and also a VW Passat GTE

**Comment by oswi82** [comment]
Hi! I have updated the iobroker with version 0.0.25. I do not get any error anymore but the values are updated only at the instance start-up and afterwards are not updating anymore since I do not stop and re-start the adapter. Any idea why?
