### ISSUE TITLE
AdBlue and oil levels stopped updating

### ISSUE THREAD

**Issue by agross** [TA2k/ioBroker.vw-connect#165]
**Describe the bug**  

AdBlue (`vw-connect.0.xxx.status.data_0x0204FFFFFF.field_0x02040C0001`) and oil levels (`vw-connect.0.xxx.status.data_0x0204FFFFFF.field_0x0204040003`) were updated in June 2021 for the last time, e.g.

![image](https://user-images.githubusercontent.com/16245/141701210-312da87f-4829-4fc8-8d16-44e90ce2d980.png)

The `9500 km` value shown above is for the AdBlue range.

I tried the VW API [with this project](https://github.com/trocotronic/weconnect) and the results were:

```
	Intervals:
                ...
		AdBlue range: 4500 km
	Oil level:
		Liters: 1.0 l
		Percentage: 0.0 %
```

**Versions:**  
 - Adapter version: 0.0.45
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: Linux

**Additional context**  

I tried enabling "Save raw JSON" but I could not find the state it is supposed to use.

**Comment by agross** [comment]
After enabling debug logging I found this in the JSON:
```json
"StoredVehicleDataResponse": {
...
        {
          "id": "0x02040C0001",
          "field": [
            {
              "id": "0x02040C0001",
              "tsCarSentUtc": "2021-11-14T17:55:34Z",
              "tsCarSent": "2021-11-14T18:55:31",
              "tsCarCaptured": "2021-11-14T09:43:08",
              "tsTssReceivedUtc": "2021-11-14T17:55:39Z",
              "milCarCaptured": 10684,
              "milCarSent": 10686,
              "value": "4500",
              "unit": "km"
            }
          ]
        },
```

**Comment by agross** [comment]
OK, when and why did this change occur?

```diff
-vw-connect.0.xxx.status.data_0x0204FFFFFF.field_0x02040C0001
+vw-connect.0.xxx.status.data_0x02040C0001.field_0x02040C0001
```

**Comment by TA2k** [comment]
I think this was changed by vw internaly we cannot influence this
