### ISSUE TITLE
Error Message with We Connect Account and Passat from 2020

### ISSUE THREAD

**Issue by STM84** [TA2k/ioBroker.vw-connect#17]
I get into Log follow Message:

  |   |   |  
-- | -- | -- | --
vw-connect.0 | 2020-06-04 12:00:12.989 | error | (6527) status update Failed
vw-connect.0 | 2020-06-04 12:00:12.987 | error | (6527) 403
vw-connect.0 | 2020-06-04 12:00:12.642 | error | (6527) get vehicle data Failed
vw-connect.0 | 2020-06-04 12:00:12.639 | error | (6527) {"error":{"errorCode":"gw.error.unknown","description":"Invalid backend error"}}
vw-connect.0 | 2020-06-04 12:00:12.636 | error | (6527) 40

PW and email are 100% right and also S-Pin are correct

**Comment by TA2k** [comment]
should be fixed in the current github version
