### ISSUE TITLE
Support for Cupra Born?

### ISSUE THREAD

**Issue by andig** [TA2k/ioBroker.vw-connect#173]
I'm working on https://evcc.io and regularly use your repos as source of information for the API flows. In my tests, the Cupra Born does work as far as authentication does, but does not appear the in the users vehicles (similar to Enyaq vs Skoda).

Is anything known about that platform?

**Comment by andig** [comment]
I've noticed that the etron implementation now supports Q4. I suspect Cupra Born may work similarly to etron, but with different credentials. Any ideas?

**Comment by TA2k** [comment]
Need an account with this car. A plain account without car is not sufficient

**Comment by andig** [comment]
Thank you. I'll try to find credentials for sharing.

**Comment by andig** [comment]
@TA2k could you email mit at info auf evcc.io? Then your email does not become public...

**Comment by TA2k** [comment]
the email is already public [tombox2020@gmail.com](mailto:tombox2020@gmail.com)
