### ISSUE TITLE
Error TripStatistic Audi A4

### ISSUE THREAD

**Issue by bertl83** [TA2k/ioBroker.vw-connect#180]
Bekomme bei meinem Audi A4 (B9 2017) leider keine Trip Daten.
Im Log hab ich folgendes:

{"error":{"errorCode":"tripstatistics.auth.forbidden","description":"not authorized for 'trip_statistic_v1:G_TRIPDATA'."}}

Kann mir dazu wer helfen?

**Comment by TA2k** [comment]
Sind die Trip daten in der App sichtbar. Scheinbar hat das Fahrzeug die Funktionalität nicht

**Comment by bertl83** [comment]
Nein, hab nix gefunden. Ok dann wirds wohl wirklich nicht unterstützt. Danke dir!
