### ISSUE TITLE
Changes to climatisation / heating on skoda

### ISSUE THREAD

**Issue by michis0806** [TA2k/ioBroker.vw-connect#20]
Hi, I'm currently using the adapter to monitor my Skoda Karoq in iobroker. I am using Yahka Homekit adapter to get some information to my iPhone. I now want to start auxiliary heating / ventilation with Yahka. I managed to start heating with the adapter with setting vw-connect.0._FIN_.remote.standheizung to true. 
My Goal would now be to get access to ventilation, too. So I did some research within the app and Charles-Proxy and found some requests:
Starting Ventilation in the App calls the URL https://msg.volkswagen.de/fs-car/bs/rs/v1/Skoda/CZ/vehicles/_FIN_/action
with the message
`{
    "performAction": {
        "quickstart": {
            "climatisationDuration": 30,
            "startMode": "ventilation",
            "active": true
        }
    }
}`

when I start heating it's 

`{
    "performAction": {
        "quickstart": {
            "climatisationDuration": 30,
            "startMode": "heating",
            "active": true
        }
    }
}`

and when I stop heating/ventilation, a call to https://msg.volkswagen.de/fs-car/bs/rs/v1/Skoda/CZ/vehicles/_FIN_/action ist fired with

`{
    "performAction": {
        "quickstop": {
            "active": false
        }
    }
}`

Is there any chance to implement that into the adapter?

Thanks
Michael

**Comment by TA2k** [comment]
I need the contenttype of the log

application/vnd.vwg.mbb.VentilationAction_v1_0_0+xml

?

**Comment by michis0806** [comment]
Content-Type: application/vnd.vwg.mbb.RemoteStandheizung_v2_0_2+json

**Comment by TA2k** [comment]
I tried a blind implementation. Please install from github and try the ventilation

**Comment by michis0806** [comment]
That was unexpected quick ;) Thanks for that!
Is it possible that you switched values? I find "startMode": "heating" in the call at "ventilation". I think it should be "startMode": "ventilation"...

**Comment by TA2k** [comment]
Is it working?
Sorry I copied the wrong one. What is the different between heating and ventilation? Window heating or Standheizung?

**Comment by TA2k** [comment]
I corrected it in the github please try again

**Comment by michis0806** [comment]
Cars with Standheizung are coming with the possibility to only ventilate the car without heating in summer. So the app provides heating (Standheizung) and ventilating (Standlüftung)

**Comment by michis0806** [comment]
Just had the chance to check it. Unfortunately it doesn't work... I'm getting a 404 in iobroker.

> 2020-06-25 09:14:11.671 - debug: vw-connect.0 (30552) { "performAction": { "quickstart": { "climatisationDuration": 30, "startMode": "ventilation", "active": true } } }
> --
> 2020-06-25 09:14:11.672 - debug: vw-connect.0 (30552) application/json; charset=UTF-8
> 2020-06-25 09:14:11.829 - error: vw-connect.0 (30552) 404
> 2020-06-25 09:14:11.830 - error: vw-connect.0 (30552) failed set state



Here's the complete header I'm getting with the app:

> POST /fs-car/bs/rs/v1/Skoda/CZ/vehicles/_FIN_/action HTTP/1.1
> Host: msg.volkswagen.de
> X-App-Id: cz.skoda-auto.connect
> X-MbbSecToken: ...
> Accept: application/json
> Authorization: Bearer ...
> Accept-Charset: utf-8
> X-App-Name: ConnectApp
> X-Language-Id: de
> Accept-Language: de-DE
> Accept-Encoding: gzip, deflate, br
> Content-Type: application/vnd.vwg.mbb.RemoteStandheizung_v2_0_2+json
> Content-Length: 101
> User-Agent: OneConnect/200605002 CFNetwork/1128 Darwin/19.6.0
> Connection: keep-alive
> X-Platform: apple
> X-Country-Id: DE
> X-App-Version: 3.4.2

**Comment by TA2k** [comment]
I tried to fix the ventilation. can you try again? is remote.standheizung working for you?

**Comment by michis0806** [comment]
Sorry, no luck here. 
setting remote.standheizung to true works for me, same for flash and honk. 
But the buttons ventilation/heating do not work... Is it intended that has
`application/vnd.vwg.mbb.RemoteStandheizung_v2_0_0+xml` 
instead of 
`application/vnd.vwg.mbb.RemoteStandheizung_v2_0_2+json`
?

**Comment by TA2k** [comment]
yes i adjusted the version number. pls try again what says the log after sending the command?

**Comment by michis0806** [comment]
Hi, sorry, I had some serious problems with my docker host, so It took some time to test this. It isn't running:
`    2020-07-03 22:37:29.455  - [35msilly[39m: vw-connect.0 (2460) States user redis pmessage vw-connect.0.*/vw-connect.0.FIN.remote.ventilation:{"val":true,"ack":false,"ts":1593808649453,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1593199241078}
    2020-07-03 22:37:29.654  - [34mdebug[39m: vw-connect.0 (2460) {"securityPinAuthInfo":{"securityToken":"....","securityPinTransmission":{"hashProcedureVersion":2,"challenge":"....."},"remainingTries":3}}
    2020-07-03 22:37:30.032  - [34mdebug[39m: vw-connect.0 (2460) [object Object]
    2020-07-03 22:37:30.033  - [34mdebug[39m: vw-connect.0 (2460) <?xml version="1.0" encoding= "UTF-8" ?>
    <performAction xmlns="http://audi.de/connect/rs">
        <quickstart>
            <active>true</active>
            <climatisationDuration>20</climatisationDuration>
            <startMode>ventilation</startMode>
        </quickstart>
    </performAction>

    2020-07-03 22:37:30.033  - [34mdebug[39m: vw-connect.0 (2460) application/vnd.vwg.mbb.RemoteStandheizung_v2_0_2+xml
    2020-07-03 22:37:30.253  - [31merror[39m: vw-connect.0 (2460) 400
    2020-07-03 22:37:30.255  - [31merror[39m: vw-connect.0 (2460) failed set state`

**Comment by lendy007** [comment]
Hello, 

I have little bit offtopic question - I am working on some plugin for HomeAssistant (different home automation platform) and I have some issues enabling heating/ventilation - I am getting `Got HTTP400; {"error":{"errorCode":"RS.technical.9026","description":"Technical validation error"}}`

I am able to send "STOP" request (action quickstop as described above) without issues and it is performed correctly.

Would you be able to give me some advice if for START I need to send also some equivalent to S-PIN which is needed by application?

Thank you

**Comment by TA2k** [comment]
please test with latest github version
