### ISSUE TITLE
Audi Q4 e-tron not showing up in userVehicle list

### ISSUE THREAD

**Issue by frankjoke** [TA2k/ioBroker.vw-connect#203]
I just checked new v0.50 and it does not support my Audi Q4 e-tron.
Audi app is working with the account.

`No Vehicles found
--
vw-connect.0 | 2022-03-25 21:42:32.061 | debug | {"userVehicles":null}
vw-connect.0 | 2022-03-25 21:42:28.605 | debug | Login successful
vw-connect.0 | 2022-03-25 21:42:25.115 | debug | Error: Invalid URI "myaudi:///#state=fc9ba86c-0340-475d-9bc1-3e9ba9f69356&access_tokenI". This can be caused by a crappy redirection.
vw-connect.0 | 2022-03-25 21:42:14.779 | debug | {"date":"Fri, 25 Mar 2022 20:42:14 GMT","content-length":"0","connection":"close","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-language":"de-DE","expires":"0","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com&relayState=28748e9f13e56050a5e9016df8e3b8a8f81b5be7&userId=b8f5de9b-d44e-4d10-987b-175d1c87eae3&HMAC=1e49ae17235fb91d9754689f619922cf8ff63a4864117d2868a0d5e76ed88b15","pragma":"no-cache","strict-transport-security":"max-age=31536000 ; includeSubDomains","x-content-type-options":"nosniff","x-frame-options":"DENY","x-vcap-request-id":"81abfb39-f5aa-47da-430a-42deed79c468","x-xss-protection":"1; mode=block"}
`

**Comment by TA2k** [comment]
Bitte audietron wählen
