### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by tollertenya** [TA2k/ioBroker.vw-connect#211]
**Describe the bug**  
Connection not possible due error in certificate chain - may related to Volkwagen/Audi
Car is Audi e-tron MY2021

**To Reproduce**  
1. Go to 'Protocoll'
2. Click on 'VW-Connect'
3. See error

**Expected behavior**  
Update values 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v0.0.51
 - JS-Controller version: 4.0.23
 - Node version: v12.22.1
 - Operating system: rasping

**Comment by TA2k** [comment]
Which car type?

**Comment by tollertenya** [comment]
It is a Audi e-tron 55 MY2021

**Comment by TA2k** [comment]
Type
Audi E-Tron I cannot see any issue during login

**Comment by tollertenya** [comment]
confirm - it works again, I guess Volkswagen IT missed to update cert chain
