### ISSUE TITLE
"Position in Adresse umwandeln" ist ohne Funktion

### ISSUE THREAD

**Issue by Marty56** [TA2k/ioBroker.vw-connect#216]
Modus "Skoda Enyaq"

Ich habe den Parameter "Position in Adresse umwandeln (nur Auswählen, wenn es genutzt wird)" angewählt. Die Koordinaten werden korrekt ermittelt, aber ein Datenpunkt mit der entsprechende Adresse wird nicht erzeugt.

Versions:

Adapter version: 0.0.53
JS-Controller version: 4.0.23
Node version: v16.17.1
Operating system: Linux Debian Bullseye

**Comment by TA2k** [comment]
wie heißt der Datenpunkt bei skoda und welchen Inhalt hat er

**Comment by Marty56** [comment]
Ich kann die Frage nicht beantworten. Weil Datenpunkte vom Adapter angelegt werden

**Comment by TA2k** [comment]
wie heißt der Datenpunkt bei skoda für die parking position und welchen Inhalt hat er?
Oder welche Positionen soll in eine Adresse umgewandelt werden?

**Comment by Marty56** [comment]
OK. Jetzt kapiere ich es. Die Datenpunkte sind nicht von Dir angelegt, sondern Du übernimmst eine Struktur, die von VW/Skoda kommt. Das erklärt auch die Redudanz. Die Datenpunkte lauten

vw-connect.0.TMBxxxxxxxxx.status.positionvehicles.parking-position.latitude
vw-connect.0.TMBxxxxxxxxx.status.positionvehicles.parking-position.longitude

**Comment by TA2k** [comment]
sollte mit GitHub jetzt gehen

**Comment by Marty56** [comment]
Danke.

**Comment by Backes89** [comment]
Moin, da würde ich mich kurz mit reinhängen, weil das Thema in die gleiche Richtung geht. Falls ich nen neues Issue machen soll, kurz schreiben.

Bei ID3/4/5 gibt's während das Auto sich bewegt den Boolean "isMoving" in der Datenstruktur. Den müsste es beim Enyaq eigentlich auch geben, taucht aber hier nicht auf. Kannst du den ggf mit aufnehmen?

**Comment by TA2k** [comment]
Wie heißt der Pfad bei id eigentlich wird alles automatisch erzeugt wenn es die app zurückgibt

wird denn sowas in der app angezeigt?

**Comment by Backes89** [comment]
Pfad beim ID lässt sich bestimmt von jemandem herausfinden im iobroker Forum im Thread zum Plug-in.

Hier nen Screenshot aus der Skoda App wenn der Enyaq in Bewegung ist. Sobald die Karre steht bzw die Zündung aus ist hat man die Adresse wo das Auto steht. 

![Screenshot_20221119-191013_MyKODA.jpg](https://user-images.githubusercontent.com/31594459/202865807-8d53353b-5608-417a-83bc-35e9d201d33e.jpg)

**Comment by Backes89** [comment]
Schau mal. Hab das hier in nem VW Forum gefunden. Hilft das weiter? 
![image](https://user-images.githubusercontent.com/31594459/202914062-d9eef873-4564-429a-849d-f2cc812fd7aa.png)

**Comment by TA2k** [comment]
mmh die id haben eine explizite ismoving aber die skoda geben einfach keine park position zurück wenn er fährt. Müsste man mal im debug log schauen was er zurück gibt wenn man fährt oder ich brauch nochmal ein account

**Comment by jfmennedy** [comment]
Wenn der Skoda fährt werden leider keine Positions- oder sonstige Updates wie Reichweite, Füllstand etc. herausgegeben. Erst wenn die Zündung aus ist werden diese Werte aktualisiert...

**Comment by Backes89** [comment]
> Wenn der Skoda fährt werden leider keine Positions- oder sonstige Updates wie Reichweite, Füllstand etc. herausgegeben. Erst wenn die Zündung aus ist werden diese Werte aktualisiert... 

Ist nicht ganz richtig. Beim Enyaq werden auch während der Fahrt Akkustand und Reichweite in der App aktualisiert. Jedenfalls mig ME3. Unter ME2 hab ichs ehrlich gesagt nie beobachtet.

Ich geh gleich mal in en Debug Modus und schaue nach was sich so findet.

**Comment by jfmennedy** [comment]
> > Wenn der Skoda fährt werden leider keine Positions- oder sonstige Updates wie Reichweite, Füllstand etc. herausgegeben. Erst wenn die Zündung aus ist werden diese Werte aktualisiert...
> 
> Ist nicht ganz richtig. Beim Enyaq werden auch während der Fahrt Akkustand und Reichweite in der App aktualisiert. Jedenfalls mig ME3. Unter ME2 hab ichs ehrlich gesagt nie beobachtet.
> 
> Ich geh gleich mal in en Debug Modus und schaue nach was sich so findet.

Ah ok, ich habe einen Oktavia, bei dem kommen die Werte nur, wenn die Zündung ausgeschaltet wurde...
