### ISSUE TITLE
Skoda Enyaq: sehr viele Fehlermeldung erzeugen unübersichtliches Log File 

### ISSUE THREAD

**Issue by Marty56** [TA2k/ioBroker.vw-connect#217]
Seit ein paar Tagen funktioniert die Abfrage für  meinen Skoda Enyaq nicht mehr. Ich benutze die Version 0.0.53.
Vielleicht hat sich das API geändert, vielleicht sind die Server von Skoda mal wieder abgeschmiert. Keine Ahnung.
Die Funktion der Connectivity im VW Konzern ist ja bekanntermaßen ziemlich instabil.

Der Adapter wirft jetzt große Mengen von Fehlermeldungen aus, so dass ich mein Log File kaum noch lesen kann.
Außerdem kann ich als Nutzer mit diesen Fehlern überhaupt nichts anfangen. Das Spiel wiederholt sich mit der Frequenz des Abfrageintervals.

Wäre es möglich, die Fehlermeldung User gerecht zu gestalten?
z.B. dass diese Fehlermeldung nur kommen, wenn der Nutzer eine detaillierte Log Stufe ausgewählt hat
und dass der Nutzer nur noch eine viel kürzere Fehlermeldung bekommt., z.b. "Skoda Server down". 

Ein Auszug
```

vw-connect.0 | 2022-11-22 07:45:55.720 | error | https://api.connect.skoda-auto.cz/api/v1/position/vehicles/TMBxxxxxxxx/parking-position
-- | -- | -- | --
vw-connect.0 | 2022-11-22 07:45:55.719 | error | AxiosError: Request failed with status code 500
vw-connect.0 | 2022-11-22 07:45:55.719 | error | "Unable to get parking position for user {3c9337a1-4f92-4bc9-945c-d091eaea1286} and vin {TMBxxxxxxxx}"
vw-connect.0 | 2022-11-22 07:45:27.022 | error | https://api.connect.skoda-auto.cz/api/v1/charging/TMBxxxxxxxxx/settings
vw-connect.0 | 2022-11-22 07:45:27.022 | error | AxiosError: Request failed with status code 500
vw-connect.0 | 2022-11-22 07:45:27.021 | error | {"errorCode":"UNKNOWN","message":"Error happened {I/O error on GET request for \"https://cardata.apps.emea.vwapps.io/vehicles/TMBxxxxxxxxx/charging/settings\": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool}"}
vw-connect.0 | 2022-11-22 07:45:19.066 | error | https://api.connect.skoda-auto.cz/api/v1/air-conditioning/TMBJxxxxxxxx/timers
vw-connect.0 | 2022-11-22 07:45:19.065 | error | AxiosError: Request failed with status code 500
vw-connect.0 | 2022-11-22 07:45:19.065 | error | {"errorCode":"UNKNOWN","message":"Error happened {I/O error on GET request for \"https://cardata.apps.emea.vwapps.io/vehicles/TMBxxxxxxxxclimatisation/timers\": Timeout waiting for connection from pool; nested exception is org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool}"}

```

**Comment by stevoboy** [comment]
Dear all,

I have similiar problems with the API? How does it look on your side?

![image](https://user-images.githubusercontent.com/84937873/214542098-2de7c34c-67f7-4e67-8991-122c731b02c3.png)
Here is my set-up:
![image](https://user-images.githubusercontent.com/84937873/214542206-2cd7afb0-8e23-41d0-9433-6c9fe3c52f19.png)

**Comment by TA2k** [comment]
500 is a server error. Please check in the app and wait a few hours

**Comment by stevoboy** [comment]
I have similiar problems every day with the Skoda API. Are they working on their API on their side or what is the issue?
If so, can we modify the adapter in such a way that the log is kept clean?

![image](https://user-images.githubusercontent.com/84937873/217523258-93bf8c71-62f4-4840-bf06-8cd28dd0f748.png)

**Comment by TA2k** [comment]
How often this message appears

**Comment by SG-2023** [comment]
I have a simmilar behaviour: 
Three error messages for missing vehicle capacity "parking position" are logged for every update request (60 sec). Log gets very crowded. However in case the error code is 412. Did not happen 3-4 months ago. Can I deactive the error message? I do not need to display the parking position.


vw-connect.0 | 2023-02-11 12:10:23.291 | error | https://api.connect.skoda-auto.cz/api/v1/position/vehicles/TMB.../parking-position
vw-connect.0 | 2023-02-11 12:10:23.291 | error | AxiosError: Request failed with status code 412
vw-connect.0 | 2023-02-11 12:10:23.291 | error | "Unable  to get parking position for user {...}  and vin {...} because required vehicle capability is  missing."

**Comment by TA2k** [comment]
this means you have no location active for you car?
Please try the github version the error should now be ignored
error 412  are ignored
error >=500 are no infos and no errors
