### ISSUE TITLE
After Audi maintenance no access anymore. Login Failed.

### ISSUE THREAD

**Issue by THEIDEACOMPANY** [TA2k/ioBroker.vw-connect#22]
**Describe the bug**  
In the last few days the myAudi Cloud Service was repeatedly unavailable. Yesterday I had to re-login to my MyAudi App. I guess there were changes in the encryption and login strategy. The Intance VW_Connect can no longer connect and remains in status yellow. 

**To Reproduce**  
**Expected behavior**
To Login
**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
[VW-Connect.log](https://github.com/TA2k/ioBroker.vw-connect/files/5061282/VW-Connect.log)

**Versions:**  
 - Adapter version: <vw-connect@0.0.16>
 - JS-Controller version: < js-controller: 3.1.6>
 - Node version: <node: v12.18.3>
 - Operating system: <Linux>

**Additional context**

**Comment by WorkoutSeven** [comment]
Same Problem for me, exactly the same log messages. Happy to help, provide more information if possible/needed 👍

**Comment by oakedcorn** [comment]
Same here. The connection remained operational until I had to restart iobroker for some other reason. Now login is failing, from what I can tell there seems to be a parsing error.

**Comment by oakedcorn** [comment]
In my case there were new terms and conditions that had to be accepted by logging in via a browser. After doing this the adapter worked as expected.

**Comment by bananajoe86** [comment]
Not working for me an myAudi. I accept the new terms and conditions in the browser but vw-connet is still yellow and is not connected with "vw-connet"

**Comment by THEIDEACOMPANY** [comment]
Still the same by me. They have change the login Web-Server to:
https://identity.vwgroup.io/signin-service/v1/signin/c7c15e7f-135c-4bd3-9875-63838616509f@apps_vw-dilab_com?relayState=c236912bd08cf97f65020e69639927a918b2ddfd

I assume that this is the root cause. Before it was something with MyAudi as Login server.

**Comment by Master-Rudi** [comment]
Still not working for me, any fixes? Thanks

**Comment by aleator83** [comment]
@TA2k are you investigeting this or need any help on this ?

**Comment by Tranquility76** [comment]
After login to the WeConnect web portal and accepting the new privacy statements, the adapter works again (after restarting the adapter).

**Comment by dmw02** [comment]
Same Error here. 
All privacy statements are accepted in myAudi.

`
vw-connect.0 | 2020-09-20 09:36:29.085 | error | (13346) Login Failed
-- | -- | -- | --
vw-connect.0 | 2020-09-20 09:36:29.084 | error | (13346) "{\"error\":\"invalid_grant\",\"error_description\":\"Invalid credentials\",\"error_code\":\"1011\"}"
vw-connect.0 | 2020-09-20 09:36:29.083 | error | (13346) 400
vw-connect.0 | 2020-09-20 09:36:29.082 | error | (13346) Failed in first login step
`
> After login to the WeConnect web portal and accepting the new privacy statements, the adapter works again (after restarting the adapter).

With Audi-ID I can not login to VW WeConnect.

**Comment by thost96** [comment]
> Same Error here.
> -All privacy statements are accepted in myAudi.
> 
> * Login information are correct.
> 
> `
> 
> vw-connect.0	2020-09-20 09:36:29.085	error	(13346) Login Failed
> vw-connect.0	2020-09-20 09:36:29.084	error	(13346) "{"error":"invalid_grant","error_description":"Invalid credentials","error_code":"1011"}"
> vw-connect.0	2020-09-20 09:36:29.083	error	(13346) 400
> vw-connect.0	2020-09-20 09:36:29.082	error	(13346) Failed in first login step
> `			
> > After login to the WeConnect web portal and accepting the new privacy statements, the adapter works again (after restarting the adapter).
> 
> With Audi-ID I can not login to VW WeConnect.

Same for my, always getting "Failed in first login step"

**Comment by zokkai** [comment]
Works after accepting new terms & conditions.
Might be a good idea to add this in adapter information.

**Comment by bananajoe86** [comment]
Still no connection here in Germany. Today I deleted my entire myAudi account, set it up again and re-entered the vehicle. The adapter "Connected to VW-Connect = false" remains

**Comment by THEIDEACOMPANY** [comment]
@TA2k: How we can support you? Since the changes on MyAudi I have no accesses anymore. It could be the same issue exist for cars from VW and it can be solved with accepting new terms & conditions but this doesn’t work for MyAudi. 
The Logon Server is a new, before it was MyAudi . 
Now it's https://identity.vwgroup.io/signin-service/v1/signin/c7c15e7f-135c-4bd3-9875-63838616509f@apps_vw-dilab_com?relayState=8d325c3c80030f7e3c28ef4ca583a6b3a9ef2f1e

**Comment by Venni27** [comment]
Same here. No longer able to login. Manual login on webpage is working. Adapter for Audi unuseable now.

**Comment by alex030** [comment]
Anything we can do to support you on getting this fixed?

**Comment by Farfar** [comment]
I am developing an integration in pyhon for Skoda Connect and came here from a few detours.
I noticed you have some problems with login, perhaps the token handling have changed for Audi as well?
Seems like Skoda is using the oauth code flow. After login a code is received that is exchanged for JWT ID Token and Access Token from identity.vwgroup something.
Only the ID Token seems to matter, for Skoda at least, since it's exchaged for a access+refresh token from the mbboauth page.
Check out the Audi Connect integration for homeassistant here on github, not sure if it's up to date since last Audi update.

**Comment by alex030** [comment]
> I am developing an integration in pyhon for Skoda Connect and came here from a few detours.
> I noticed you have some problems with login, perhaps the token handling have changed for Audi as well?
> Seems like Skoda is using the oauth code flow. After login a code is received that is exchanged for JWT ID Token and Access Token from identity.vwgroup something.
> Only the ID Token seems to matter, for Skoda at least, since it's exchaged for a access+refresh token from the mbboauth page.
> Check out the Audi Connect integration for homeassistant here on github, not sure if it's up to date since last Audi update.

I checked the homeassistant integration and there it works. Seems like authentication is updated there.

**Comment by THEIDEACOMPANY** [comment]
@alex030 & @TA2k 
Can we support you to solve the problem in connection to Audi?

**Comment by alex030** [comment]
@THEIDEACOMPANY yes sure on my side. But it is more the question on how I can support you to get this fixed. I am open to test. Thanks

**Comment by Wolf200** [comment]
Same Problem here not able to login due to invalid credentials- myaudi is working. Hope we can get this fixed soon. Willing to test 😊

**Comment by TA2k** [comment]
fixed

**Comment by alex030** [comment]
> fixed

Works. Thanks!

**Comment by rs38** [comment]
can you please link to the change/fix commit?
