### ISSUE TITLE
Failed to get token Seat Mii

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.vw-connect#225]
**Describe the bug**  
Der Adapter verbindet sich nicht mit dem Seat Mii. Bislang hatte nie Probleme.

Der Log sagt folgendes 

vw-connect.0
2023-01-01 22:41:47.004	error	Restart Adapter in 30min

vw-connect.0
2023-01-01 22:41:47.004	error	Login Failed

vw-connect.0
2023-01-01 22:41:47.003	error	"{\"description\":\"Invalid identity token.\",\"errorCode\":\"REQUEST_DATA_INVALID\"}"

vw-connect.0
2023-01-01 22:41:47.003	error	400

vw-connect.0
2023-01-01 22:41:47.002	error	Failed to get token

vw-connect.0

**Comment by TA2k** [comment]
Welche Type verwendest du Seat Connect?

**Comment by ingiz71** [comment]
Ich habe das gleiche Problem mit meinem Skoda Enyaq. Ich verwende die Adapterversion 0.0.56. Ich vermute das Problem ist seit dem Update von IOBroker auf Version 4.0.24 da. Ich verwende VW Connect.

**Comment by DarthPride** [comment]
Ich habe dasselbe Problem mit der VW Connect App und einem Golf VIII GTE.
Hat bis gestern problemlos funktioniert.
Adapterversion 0.0.56, ich bin im ioBroker noch bei Version 4.0.23

**Comment by fuchs-1978** [comment]
> Welche Type verwendest du Seat Connect?

Bei Type habe ich Seat ausgewählt, Version 0.0.56

**Comment by josefholdschick** [comment]
Ich habe das selbe Problem mit Skoda und meinem E-Citigo.
Ich verwende die Version 0.0.56 und IOBroker in der Version 4.0.23.
Bis 31.12.22 hat alles funktioniert, habe Fehlermeldungen seit 01.01.23.

vw-connect.0 | 2023-01-02 06:18:43.686 | error | Restart Adapter in 30min
-- | -- | -- | --
vw-connect.0 | 2023-01-02 06:18:43.686 | error | Login Failed
vw-connect.0 | 2023-01-02 06:18:43.684 | error | "{\"description\":\"Invalid identity token.\",\"errorCode\":\"REQUEST_DATA_INVALID\"}"
vw-connect.0 | 2023-01-02 06:18:43.684 | error | 400
vw-connect.0 | 2023-01-02 06:18:43.682 | error | Failed to get token
vw-connect.0 | 2023-01-02 06:18:41.360 | info | starting. Version 0.0.56 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v16.17.1, js-controller: 4.0.23
vw-connect.0 | 2023-01-02 06:18:07.668 | info | Terminated (NO_ERROR): Without reason
vw-connect.0 | 2023-01-02 06:18:07.663 | info | terminating
vw-connect.0 | 2023-01-02 06:18:07.647 | info | cleaned everything up...
vw-connect.0 | 2023-01-02 06:18:07.642 | warn | Restart initiated
vw-connect.0 | 2023-01-02 06:18:07.639 | error | Restart adapter
vw-connect.0 | 2023-01-02 05:48:07.638 | error | Restart Adapter in 30min
vw-connect.0 | 2023-01-02 05:48:07.637 | error | Login Failed
vw-connect.0 | 2023-01-02 05:48:07.636 | error | "{\"description\":\"Invalid identity token.\",\"errorCode\":\"REQUEST_DATA_INVALID\"}"
vw-connect.0 | 2023-01-02 05:48:07.635 | error | 400
vw-connect.0 | 2023-01-02 05:48:07.634 | error | Failed to get token
vw-connect.0 | 2023-01-02 05:48:05.420 | info | starting. Version 0.0.56 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v16.17.1, js-controller: 4.0.23
vw-connect.0 | 2023-01-02 05:47:31.608 | info | Terminated (NO_ERROR): Without reason
vw-connect.0 | 2023-01-02 05:47:31.605 | info | terminating
vw-connect.0 | 2023-01-02 05:47:31.596 | info | cleaned everything up...
vw-connect.0 | 2023-01-02 05:47:31.594 | warn | Restart initiated

**Comment by TA2k** [comment]
@fuchs-1978 Login via Seat app geht bei mir zur zeit auch nicht

**Comment by fuchs-1978** [comment]
> @fuchs-1978 Login via Seat app geht bei mir zur zeit auch nicht

Ich kann mich einloggen, muss aber jedesmal mich neu anmelden

**Comment by flispy** [comment]
Weder die APP auf dem Handy noch die Instanz bei Biobroker funktionieren bei mir (VW Tiguan)

**Comment by w0nk1** [comment]
Das selbige seit kurzem auch bei mit mit VW Connect und meinem Passat GTE. 

`Failed to get token`

Lief aber alles ohne Probleme, muss also irgendeine Änderung auf Serverseite stattgefunden haben?

**Comment by andig** [comment]
See https://github.com/lendy007/skodaconnect/issues/64 for related discussion. The `tokenrefreshservice` seems deprecated.

**Comment by TA2k** [comment]
VW fixed the issue for VW and Seat

**Comment by fuchs-1978** [comment]
> VW fixed the issue for VW and Seat

Thank you very much an a great start into.the new year

**Comment by andig** [comment]
Happy New Year :)

**Comment by andig** [comment]
> VW fixed the issue for VW and Seat

They've fixed it for Skoda, too. Working without the latest commits.

**Comment by Farfar** [comment]
The "TokenRefreshService" is a common endpoint for all VAG brands and used for exchanging authorization codes for long lived JWT tokens.

At least version 5.2.7 of the MySkoda Android app have new endpoint (version 3.x and 4.x use the TokenRefreshService) for token exchange. This leads me to believe that the change was planned and even though it got reverted it't probable that it will be disabled again in the future.

**Comment by JockeyDoe** [comment]
> Ich habe dasselbe Problem mit der VW Connect App und einem Golf VIII GTE. Hat bis gestern problemlos funktioniert. Adapterversion 0.0.56, ich bin im ioBroker noch bei Version 4.0.23

Hatte das selbe Problem mit dem gleichen Auto, funktioniert jetzt wieder tadellos ohne, dass ich irgendetwas verändert habe.
