### ISSUE TITLE
Signin Service failed

### ISSUE THREAD

**Issue by ChristophsMowL** [TA2k/ioBroker.vw-connect#231]
vw-connect.0 | 2023-02-15 20:25:18.154 | error | 405
-- | -- | -- | --
vw-connect.0 | 2023-02-15 20:25:18.153 | warn | Failed to auto accept
vw-connect.0 | 2023-02-15 20:25:17.660 | error | Restart Adapter in 30min
vw-connect.0 | 2023-02-15 20:25:17.660 | error | Login Failed
vw-connect.0 | 2023-02-15 20:25:17.655 | warn | Try to auto accept new consent

**Comment by TA2k** [comment]
The log says logout and login into the app to accept the consent
