### ISSUE TITLE
Stati der Fenster vertauscht?

### ISSUE THREAD

**Issue by MikeEcho0815** [TA2k/ioBroker.vw-connect#233]
Moin!

Kann es sein, dass der Status der Türen etc. falsch beschrieben ist?

Ich denke, die richtigen Stati sollten sein: 1 = open, 2 = closed, 3 = locked. 
Also "closed" und "locked" sind in der ReadME vertauscht.

Gruss
Mike

**Comment by TA2k** [comment]
Das wird noch falsch dargestellt. @Sneak-L8  arbeitet daran

**Comment by Sneak-L8** [comment]
> Das wird noch falsch dargestellt. @Sneak-L8 arbeitet daran

Ich glaube, das ist ein anderes Problem. Ich kümmere mich um die doppelten Einträge bei den ID. Modellen.
Dort gibt es nur Texte, keine Zahlen.
@MikeEcho0815 um was für ein Fahrzeug(Typ) geht es?
