### ISSUE TITLE
Fehlermeldung: Failed in receive login url

### ISSUE THREAD

**Issue by dako0815** [TA2k/ioBroker.vw-connect#234]
Folgende Fehlermeldung steht im Log:
![image](https://user-images.githubusercontent.com/78207468/221670011-23d07a87-e148-4d50-ab02-2ddf12db40d7.png)

Adapter Neustart bringt nichts
Erneutes einloggen in der we connect app auch nicht

**Comment by ChristophsMowL** [comment]
+1
I installed version 0.0.60 afterwards but I still got this message

**Comment by TA2k** [comment]
Bitte nochmal die github version testen

**Comment by ChristophsMowL** [comment]
0.0.61 hat den Fehler bei mir behoben. Adapter verbindet wieder mit "Gerät und Dienst".

Danke

**Comment by dako0815** [comment]
Das kann ich auch bestätigen. Mit 0.0.61 läufts wieder einwandfrei! Top Support. Danke dafür!
