### ISSUE TITLE
Question: Is this object tree looking ok?

### ISSUE THREAD

**Issue by dp20eic** [TA2k/ioBroker.vw-connect#235]
Hello,

I have a question, I use this adapter, Version 0.0.61 in combination with a Golf build in 2022 but the object tree looks for me strange as I see for ID models it looks different.
This are picture from my `Object Tree`
![grafik](https://user-images.githubusercontent.com/71387331/221804605-3c95411a-078a-44de-b0a2-7560a5cbfc5e.png)
![grafik](https://user-images.githubusercontent.com/71387331/221804820-4630ed72-1715-4c34-b032-cf57f5f87280.png)

So is it true that I get below `Status` only the name as shown in the pictures above or is it possible to get it like in the following picture, I take from `iobroker Forum post`
This looks like an `Object Tree` from someone with an VW - ID
![grafik](https://user-images.githubusercontent.com/71387331/221806104-ad0ec15d-170b-48cf-a22a-6f20a5f097cf.png)

I would like to have the same spoken object ID names :)
If it is an issue, than I will open a new or change this from question in to a issue.

with kindly regards
Bernd

**Comment by TA2k** [comment]
The API deliveres the data in a different way. The adapter only shows the received value structure because the effort to change the structure is too high

**Comment by dp20eic** [comment]
Thank you
