### ISSUE TITLE
After change to VWv2 - no details about vehicle

### ISSUE THREAD

**Issue by ExecuteGK** [TA2k/ioBroker.vw-connect#239]
After changing the Adapter to the Type VWv2 due to login issues using the ID Login, the Adapter logs in, pulls the personal data (name, DoB, etc) but NO Data from the car (ID.4)

- delete all existing Objects,
- migrate login to VWv2
- start adapter

**Expected behavior**  
Car data is populated (SoC, charge state, etc.)

**Versions:**  
 - Adapter version: 0.62
 - JS-Controller version: 4.0.24
 - Node version: v14.18.2
 - Operating system: Ubuntu

Regards,

Sebastian

**Comment by TA2k** [comment]
Please use latest version with type id

**Comment by ExecuteGK** [comment]
Solved. I used the latest version. 

Due to the URL  change of the Volkswagen backend, the requests were blocked by the Next Gen Firewall classifying this URL as undecided safe.

It would be nice if this API remains stable for a while, or if VW would notify the Open Source community.

Thanks for your great work.

Regards

Sebastian
