### ISSUE TITLE
Vw Connect Go - error 500 Get Vehicles failed

### ISSUE THREAD

**Issue by Makobe** [TA2k/ioBroker.vw-connect#241]
Login über den Adapter funktioniert, jedoch werden keine Fahrzeugdaten geladen.
im Log erhalte ich folgende Meldungen:

vw-connect.0 | 2023-03-08 10:32:55.881 | error | Get Vehicles Failed
vw-connect.0 | 2023-03-08 10:32:55.881 | error | 500
vw-connect.0 | 2023-03-08 10:32:55.881 | error | "<!doctype html><html lang=\"en\"><head><title>HTTP Status 500 – Internal Server Error</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>"

Adapter ist in der Version 0.0.62
Dataplug auf aktuellstem Stand und App auch verbunden.
An- und Abmelden über die App schon probiert.

**Comment by TA2k** [comment]
Einfach 1 Tag abwarten

**Comment by Makobe** [comment]
Auch nach zwei Tagen warten, der selbige Fehler.

**Comment by TA2k** [comment]
Ich kann mich auch in der App nicht einloggen

**Comment by Makobe** [comment]
Okay, dann bleibt wohl erstmal warten bis die App wieder 100% funktioniert.
