### ISSUE TITLE
vw-connect.0.<vin>.statusrawJson is missing values

### ISSUE THREAD

**Issue by hpoeppel** [TA2k/ioBroker.vw-connect#245]
**Describe the bug**  
The Object vw-connect.0.<vin>.statusrawJson is missing values, for example plugConnectionState, or plugLockState.

**To Reproduce**  
I have a Cupra Born from 01.2023, everything else is working fine.

**Expected behavior**  
I would expect that the raw json is including all values that the adapter is able to show.

**Screenshots & Logfiles**  
{"engines":{"primary":{"type":"EV","fuelType":"EV","range":{"value":245,"unit":"Km"},"level":70},"secondary":{"type":null,"fuelType":null,"range":null,"level":null}},"measurements":{"mileageKm":1777},"services":{"charging":{"status":"Charging","targetPct":80,"chargeMode":"manual","active":true,"remainingTime":55,"progressBarPct":88},"climatisation":{"status":"Off","targetTemperatureKelvin":295.15,"active":false,"remainingTime":0,"progressBarPct":0}}}

**Versions:**  
 - Adapter version: v0.0.62
    Plattform: linux
    Betriebssystem: linux
    Architektur: x64
    CPUs: 2
    Geschwindigkeit: 1996 MHz
    Modell: Intel(R) Celeron(R) J4025 CPU @ 2.00GHz
    RAM: 3.8 GB
    System-Betriebszeit: 47 T. 02:08:58
    Node.js: v16.19.0
    time: 1679212187783
    timeOffset: --
    Adapter-Anzahl: 470
    NPM: 8.19.3
    Datenträgergröße: 47.9 GB
    Freier Festplattenspeicher: 37.6 GB
    Betriebszeit: 5 T. 05:29:13
    Aktive Instanzen: 7
    Pfad: /opt/iobroker/

**Comment by TA2k** [comment]
das ist eigentlich identisch du kannst ml zum testen den ordner status löschen und adapter neustarten und schauen was erstellt wird

**Comment by hpoeppel** [comment]
Wo finde ich denn den Status Ordner? Ich habe den Adapter einmal vollständig gelöscht und wieder neu erstellt, das hat aber nichts am rawjson geändert.

**Comment by TA2k** [comment]
Wo siehst du denn dann plugConnectionState

**Comment by hpoeppel** [comment]
![grafik](https://user-images.githubusercontent.com/8066256/226203147-e184b94a-d3d6-4d33-b5e9-edd798b8d7bd.png)
Ich glaube jetzt weiß ich auch welchen Status Ordner du meinst, ich hatte schon irgendwas im Dateisystem gesucht...
Den Status Ordner und auch alles andere habe ich jetzt auch einmal gelöscht und den Adapter neu gestartet, aber da kommen immer nur die gleichen Werte. 

{"engines":{"primary":{"type":"EV","fuelType":"EV","range":{"value":278,"unit":"Km"},"level":80},"secondary":{"type":null,"fuelType":null,"range":null,"level":null}},"measurements":{"mileageKm":1777},"services":{"charging":{"status":"ReadyForCharging","targetPct":80,"chargeMode":"manual","active":false,"remainingTime":0,"progressBarPct":100},"climatisation":{"status":"Off","targetTemperatureKelvin":295.15,"active":false,"remainingTime":0,"progressBarPct":0}}}

**Comment by TA2k** [comment]
teste mal die GitHub version

**Comment by hpoeppel** [comment]
Sieht super aus, vielen Dank.

{"battery":{"carCapturedTimestamp":"2023-03-22T15:08:47Z","currentSOC_pct":53,"cruisingRangeElectric_km":174},"charging":{"carCapturedTimestamp":"2023-03-22T15:08:47Z","chargingState":"notReadyForCharging","chargeType":"invalid","chargeMode":"manual","chargingSettings":"default","remainingChargingTimeToComplete_min":0,"chargePower_kW":0,"chargeRate_kmph":0},"plug":{"carCapturedTimestamp":"2023-03-22T15:08:56Z","plugConnectionState":"disconnected","plugLockState":"unlocked","externalPower":"unavailable"}}
