### ISSUE TITLE
Audi get vehicles broken

### ISSUE THREAD

**Issue by andig** [TA2k/ioBroker.vw-connect#255]
**Describe the bug**  

    Get Vehicles Failed
    403
    {"error":{"errorCode":"RS.security.9007","description":"The context has not gained a legitimation due to missing access rights."}} 

**To Reproduce**  
1. Setup type `audi`

**Expected behavior**  
no error

**Versions:**  
 - Adapter version: 0.0.67

**Comment by andig** [comment]
Workaround: use

    type: etron

**Comment by andig** [comment]
Welches Modell liefert keine Werte? Q5 Hybrid geht.

**Comment by intruder7777** [comment]
A4 Avant

**Comment by stiwy18** [comment]
Gleiches bei mir, A6 TFSIe, kein Login möglich, mit etron bekomme ich keine Fehlermeldung, jedoch auch wesentlich weniger Werte (z.B. ob die Standheizung gerade an ist)

**Comment by TA2k** [comment]
Ich brauch ein account um das zu fixen
tombox2020@gmail.com

**Comment by 0x1234567890** [comment]
Habe das gleiche Problem beim A4 Avant. 
403: {"error":{"errorCode":"RS.security.9007","description":"The context has not gained a legitimation due to missing access rights."}}


Problem besteht seit heute. Jemand eine Lösung?

**Comment by andig** [comment]
Siehe https://github.com/TA2k/ioBroker.vw-connect/issues/255#issuecomment-1586320997

**Comment by 0x1234567890** [comment]
Wieso brauch man einen Account zum fixen? Wenn ich es auf Audi etron stelle habe ich nicht mehr meine Reichweite/Tankfüllung in % im Datensatz

**Comment by andig** [comment]
Prima, dann hast du die Lösung ja

**Comment by 0x1234567890** [comment]
Aber ich habe nicht mehr alle Werte unter Audi ETron die ich verwende. Ich bekomme ich denn wieder zugriff darauf

**Comment by andig** [comment]
Siehe https://github.com/TA2k/ioBroker.vw-connect/issues/255#issuecomment-1586320997

**Comment by tkreuti** [comment]
Audi Q3 F3 (2021) liefert seit 9.06.2023 auch keine Werte. Hoffe auf Lösung...

**Comment by 0x1234567890** [comment]
> > Hoffe auf Lösung...
> 
> Die Lösung habe ich oben jetzt 2x verlinkt: es braucht Testcredentials. Weitere "me too" Postings werden daran nichts ändern...

Was für testcredentials? Wofür? Woher? Ein Paar mehr Infos zum verstehen wären gut.

Und auf etron umstellen ist keine Lösung wenn nicht alle Daten ankommen.

**Comment by andig** [comment]
> Wofür?

Natürlich für das Fahrzeug, wofür sonst wenn es um Fehler mit der Fahrzeugintegration geht?

**Comment by fornax76-git** [comment]
> > > Hoffe auf Lösung...
> > 
> > 
> > Die Lösung habe ich oben jetzt 2x verlinkt: es braucht Testcredentials. Weitere "me too" Postings werden daran nichts ändern...
> 
> Was für testcredentials? Wofür? Woher? Ein Paar mehr Infos zum verstehen wären gut. Außerdem markierst du einen Beitrag von jemanden der das gleiche problem hat und seine Email adresse dagelassen hat… was soll mir das sagen?
> 
> Und auf etron umstellen ist keine Lösung wenn nicht alle Daten ankommen.

Der markierte Beitrag ist vom Programmierer des Adapters ;-)
Er benötigt einen Accountzugang (weil er selber vermutlich keinen Audi hat) um den Fehler zu ermitteln.

**Comment by andig** [comment]
Natürlich kann man jeden Kommentar mit "Daumen runter" markieren, oder man versucht etwas zur Lösung beizutragen @0x1234567890

**Comment by stiwy18** [comment]
Guten Morgen AndiG, 
hilft es dir, wenn ich dir per Teamviewer Zugang zu meinem Laptop gebe? Wireshark ist natürlich installiert. 
VG Stefan

**Comment by TA2k** [comment]
Fix with v0.0.70

**Comment by andig** [comment]
@TA2k we‘re effectively switching to etron as I did with evcc, right? Seems that the original Audi integration is dead now?

**Comment by TA2k** [comment]
Correct the % fuel was missing because it was the same key in the extraction logic

**Comment by StrichcodePG** [comment]
I'm still missing so many entries, like long- and shortterm tripdata, average consumptions...
Also I can't control my climate, the remote.climatisationv2 is also missing. The lock and unlock capability is also missing.
Any chance to get this working again?

**Comment by fornax76-git** [comment]
> I'm still missing so many entries, like long- and shortterm tripdata, average consumptions... Also I can't control my climate, the remote.climatisationv2 is also missing. The lock and unlock capability is also missing. Any chance to get this working again?

Hi, I had the same problem.
I stopped the adapter, deleted the hole objecttree and started the adapter again.
After that I found all the missing data, but in a different structure.

**Comment by StrichcodePG** [comment]
> > I'm still missing so many entries, like long- and shortterm tripdata, average consumptions... Also I can't control my climate, the remote.climatisationv2 is also missing. The lock and unlock capability is also missing. Any chance to get this working again?
> 
> Hi, I had the same problem. I stopped the adapter, deleted the hole objecttree and started the adapter again. After that I found all the missing data, but in a different structure.

Nope, did the same, but the mentioned data is missing in the new structure.

**Comment by TA2k** [comment]
vw-connect.0.ID.status.rangeStatus.primaryEngine.currentFuelLevel_pct

**Comment by MrLee99** [comment]
MoiN! 

Die neue Struktur ist top!
Allerdings ahabe ich mal wieer Probleme mit der Klimaanlage:
<html>
<body>


vw-connect.0 | 2023-06-19 11:15:38.508 | error | failed set state climatisation
-- | -- | -- | --
vw-connect.0 | 2023-06-19 11:15:38.507 | error | {"error":{"message":"Not Found","info":"Upstream service responded with an unexpected status. If the problem persists, please contact our support.","code":4112,"group":2,"retry":true}}
vw-connect.0 | 2023-06-19 11:15:38.505 | error | 404


</body>
</html

bisher habe ich climatisationV3 verwendet...aktuelle versuche ich remote/climatisation...

bis denne
Mr.LEe/Christian

**Comment by RalphSester** [comment]
> Fix with v0.0.70

Hi @TA2k ,

there is the same error with the audi-binding in OpenHAB at this time.
Can you tell me, what do have done to fix this problem in IOBroker, so I can give the binding-developer in OpenHAB some hints... thank you!

**Comment by andig** [comment]
Seems the Audi auth is simply no longer supported. You'll need to switch to etron.

**Comment by el-Presi** [comment]
Ja das selbe hier. Q5 Hybrid - kann keine Klima mehr starten - es gibt ja nur noch "vw-connect.0.123.remote.climatisation" in der neuen Struktur. Dieser Datenpunkt macht allerdings gar nichts.
Ich hatte vorher "...climatisationv2" genutzt.
