### ISSUE TITLE
Enyaq: No Token received

### ISSUE THREAD

**Issue by andig** [TA2k/ioBroker.vw-connect#258]
Enyaq (but also Skoda) Login fails with latest adapter:

vw-connect.0 | 2023-06-29 14:03:20.727 | error | No Token received. Please try to logout and login in the VW app or select type VWv2 in the settings
-- | -- | -- | --
vw-connect.0 | 2023-06-29 14:03:20.554 | info | https://identity.vwgroup.io/signin-service/v1/consent/users/f419072e-e30c-45a3-97b4-c25660a5c190/f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com?scopes=openid%20mbb%20profile&relayState=8e37675822428dca90a470f833beaf4795791e62&callback=https://identity.vwgroup.io/oidc/v1/oauth/client/callback&hmac=4a7297740614e3ef46d9ec3e7f7208d1253f58a2c01effe3f8ce252ba4058ace
vw-connect.0 | 2023-06-29 14:03:20.554 | warn | No Token received visiting url and accept the permissions or login and accept
vw-connect.0 | 2023-06-29 14:03:19.005

I have the same issue locally. Some Skodas work, some don't. It is not a T&C problem.

@TA2k can I email you credentials?

**Comment by fuchs-1978** [comment]
I have also a Problem with Seat Mii

vw-connect.0 | 2023-06-29 19:00:07.447 | error | Restart Adapter in 30min
-- | -- | -- | --
vw-connect.0 | 2023-06-29 19:00:07.447 | error | Login Failed
vw-connect.0 | 2023-06-29 19:00:07.446 | error | "{\"description\":\"IdentityKit Response: 401 : {\\\"error\\\":\\\"invalid_client\\\",\\\"error_description\\\":\\\"Client authentication failed\\\"}\",\"errorCode\":\"IDENTITY_KIT_RESPONSE_ERROR\"}"
vw-connect.0 | 2023-06-29 19:00:07.446 | error | 401
vw-connect.0 | 2023-06-29 19:00:07.445 | error | Failed to get token

**Comment by andig** [comment]
This is not about Seat…

**Comment by andig** [comment]
@TA2k do you need credentials for testing?

**Comment by andig** [comment]
See https://github.com/evcc-io/evcc/discussions/8570#discussioncomment-6352050 for more details.

**Comment by andig** [comment]
No reply, closing.
