### ISSUE TITLE
Seat Mii - Login failed 

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.vw-connect#259]

**Comment by fuchs-1978** [comment]
I have also a Problem with Seat Mii

vw-connect.0 | 2023-06-29 19:00:07.447 | error | Restart Adapter in 30min
-- | -- | -- | --
vw-connect.0 | 2023-06-29 19:00:07.447 | error | Login Failed
vw-connect.0 | 2023-06-29 19:00:07.446 | error | "{\"description\":\"IdentityKit Response: 401 : {\\\"error\\\":\\\"invalid_client\\\",\\\"error_description\\\":\\\"Client authentication failed\\\"}\",\"errorCode\":\"IDENTITY_KIT_RESPONSE_ERROR\"}"
vw-connect.0 | 2023-06-29 19:00:07.446 | error | 401
vw-connect.0 | 2023-06-29 19:00:07.445 | error | Failed to get token

**Comment by TimoGoerlich** [comment]
Habe sasselbe Problem mit dem Formentor

**Comment by ty6600** [comment]
Same with my Leon

**Comment by bembelstemmer** [comment]
Just had the same issue mith my Mii.
I changed the Type from "Seat" to "Seat Cupra #2 Alternative". Now it's working again for me.
Seems like some API changes were done on VW side.

**Comment by ty6600** [comment]
Thank you!

**Comment by fuchs-1978** [comment]
> Just had the same issue mith my Mii. I changed the Type from "Seat" to "Seat Cupra #2 Alternative". Now it's working again for me. Seems like some API changes were done on VW side.

Thank you 🥰

**Comment by martijnpoppen** [comment]
See: https://github.com/TA2k/ioBroker.vw-connect/pull/265
