### ISSUE TITLE
SOC (state of charge) isn't adjustable

### ISSUE THREAD

**Issue by GermanSheepDog** [TA2k/ioBroker.vw-connect#267]
I would like to set the SOC on my Audi e-tron to 90% and change this object in iobroker:
1. Initial position: The SOC is set to 80.
2. I change this object to 90:
`
vw-connect.0.WAUZZZGE4MB026112.status.chargingSettings.targetSOC_pct
`
3. The object shows the value 90 and the correct value can also be read out via a script.
4. After the next refresh of the adapter, the value is returned to the old value.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Comment by GermanSheepDog** [comment]
My versions:

- Adapter version: 0.0.67
- Node: v14.21.3
- Operating system: Linux ubuntu 5.15.0-76-generic

**Comment by andig** [comment]
To adjust that you'll need to charge the battery ;)
