### ISSUE TITLE
vw-connect adapter for ioBroker does not work anymore at least with Skoda Enyaq

### ISSUE THREAD

**Issue by ingiz71** [TA2k/ioBroker.vw-connect#270]
Since some days ago I recognized, that datapoints are not updated anymore. I updated the adapter from version 0.0.67 to 0.0.72. Unfortunately same behavior. Then I uninstalled the instance and the adapter and installed it again (also with both versions). The adapter connects and gets green but it don’t get any datapoints except the connection point. I've documented everything in the attached screenshots. 
Regards
![Systeminformation](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/e546b401-d276-4d14-9c93-c20dd03f5274)
![Objekte](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/f0c3b42a-e620-48b9-8211-2f6fb77b363c)
![Fehlermeldung](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/c38dec32-6e24-49c7-ad6e-8a826c56e84b)
![Settings](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/dd37598c-d9c1-46d6-a243-c73e27870924)
![Instanzen](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/12443974-e8b9-44aa-8230-f29c31eb5980)

**Comment by ASdiagnose** [comment]
Update to the last version 0.1.0 - and It works 
have the same

**Comment by ingiz71** [comment]
Thx. Version 0.1.0 works! Just the points for the parking position (.status.positionvehicles.parking-position.longitude & .status.positionvehicles.parking-position.latitude) are not there anymore or am I missing something?

**Comment by TA2k** [comment]
Please delete all objects and see what's recreated after adapter restart

**Comment by OE5PON** [comment]
Same issue with Seat Mii here, Update 0.1.0 didn't solve.
![image](https://github.com/TA2k/ioBroker.vw-connect/assets/46243997/083eefa3-fc69-4d4c-9aa1-afdc3c9d2422)

**Comment by fuchs-1978** [comment]
> Same issue with Seat Mii here, Update 0.1.0 didn't solve. ![image](https://user-images.githubusercontent.com/46243997/265217088-083eefa3-fc69-4d4c-9aa1-afdc3c9d2422.png)

Nutze die letze Version von GitHub, die läuft wieder

**Comment by OE5PON** [comment]
Danke, funktioniert wieder!

**Comment by ingiz71** [comment]
Nothing changed after deleting and recreating all objects. The points for the parking postion are still missing. The entire folder .status.positionvehicles is not existing anymore.

![points](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/440a9adf-7f71-4c07-8740-0f48213f8801)

**Comment by TA2k** [comment]
Which car type is selected. Is the log have information?

**Comment by ingiz71** [comment]
For some reason, the parking position points are suddenly there this morning. Everthing works. Thanks for your great support!
![p2](https://github.com/TA2k/ioBroker.vw-connect/assets/59662851/0ee6ac17-41dc-496e-8612-9c0a38194d96)
