### ISSUE TITLE
Connecting to cupra suddenly stopped working. (certificate has expired) ?

### ISSUE THREAD

**Issue by jb-io** [TA2k/ioBroker.vw-connect#272]
Connecting to cupra suddenly stopped working.

Until 31.August i could connect to my cupra with cupra protocol v2
Then suddenly i could not get any information anymore (without having changed anything) [App still works correctly]

# Log with **Seat Cupra 2 Alternative** (Worked before 31.Aug)
vw-connect.0 | 2023-09-10 12:33:18.164 | error | Get Vehicles Failed
-- | -- | -- | --
vw-connect.0 | 2023-09-10 12:33:18.164 | error | 403
vw-connect.0 | 2023-09-10 12:33:18.164 | error | {"error":{"errorCode":"mbbc.rolesandrights.invalidUserId","description":"The userId in the path (undefined) and the userId in the authorization context (ae7**********************50) did not match."}}
vw-connect.0 | 2023-09-10 12:33:18.006 | error | Error: certificate has expired
vw-connect.0 | 2023-09-10 12:33:17.760 | info | Login successful
vw-connect.0 | 2023-09-10 12:33:17.315 | debug | Error: Invalid protocol: cupraconnect:
vw-connect.0 | 2023-09-10 12:33:16.899 | debug | {"date":"Sun, 10 Sep 2023 10:33:16 GMT","content-length":"0","connection":"close","apigw-requestid":"L**************=","x-content-type-options":"nosniff","x-xss-protection":"0","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","expires":"0","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-frame-options":"DENY","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=00000000-0000-0000-0000-000000000000@apps_vw-dilab_com&relayState=9**************************************1&userId=00000000-0000-0000-0000-000000000000&HMAC=f**************************************************************0","content-language":"en-US"}
vw-connect.0 | 2023-09-10 12:33:16.899 | debug | ""
vw-connect.0 | 2023-09-10 12:33:16.546 | debug | emailPasswordForm2
vw-connect.0 | 2023-09-10 12:33:16.279 | debug | parseEmailForm
vw-connect.0 | 2023-09-10 12:33:15.985 | info | Login in with seatcupra2
vw-connect.0 | 2023-09-10 12:33:15.973 | info | starting. Version 0.0.67 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v16.20.1, js-controller: 4.0.24
vw-connect.0 | 2023-09-10 12:33:15.865 | debug | Plugin sentry Initialize Plugin (enabled=true)

# Log with **Seat Cupra** (Chould not get it to work in the past)
vw-connect.0 | 2023-09-10 12:28:22.397 | info | Found 0 vehicles
-- | -- | -- | --
vw-connect.0 | 2023-09-10 12:28:22.397 | debug | {"vehicles":[]}
vw-connect.0 | 2023-09-10 12:28:16.448 | info | Login successful
vw-connect.0 | 2023-09-10 12:28:16.305 | debug | Error: Invalid protocol: cupra:
vw-connect.0 | 2023-09-10 12:28:15.866 | debug | {"date":"Sun, 10 Sep 2023 10:28:15 GMT","content-length":"0","connection":"close","apigw-requestid":"L**************=","x-content-type-options":"nosniff","x-xss-protection":"0","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","expires":"0","strict-transport-security":"max-age=31536000; includeSubDomains; preload","x-frame-options":"DENY","location":"https://identity.vwgroup.io/oidc/v1/oauth/sso?clientId=00000000-0000-0000-0000-000000000000@apps_vw-dilab_com&relayState=4**************************************e&userId=00000000-0000-0000-0000-000000000000&HMAC=f**************************************************************0","content-language":"en-US"}
vw-connect.0 | 2023-09-10 12:28:15.866 | debug | ""
vw-connect.0 | 2023-09-10 12:28:15.563 | debug | emailPasswordForm2
vw-connect.0 | 2023-09-10 12:28:15.323 | debug | parseEmailForm
vw-connect.0 | 2023-09-10 12:28:15.011 | info | Login in with seatcupra
vw-connect.0 | 2023-09-10 12:28:14.996 | info | starting. Version 0.0.67 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v16.20.1, js-controller: 4.0.24
vw-connect.0 | 2023-09-10 12:28:14.885 | debug | Plugin sentry Initialize Plugin (enabled=true)

**Comment by TA2k** [comment]
bitte beta repo verwenden

**Comment by jb-io** [comment]
Nachdem ich realisiert habe, dass es mittlerweile ein minor update gab und 0.0.72 nicht mehr die neuste Version ist, konnte ich auch auf die aktuellste version aktualisieren.
`iobroker upgrade iobroker.vw-connect@0.1.2`

https://www.npmjs.com/package/iobroker.vw-connect/v/0.1.2?activeTab=versions

* Fehler ist weg
* Fahrzeugdaten werden wieder geladen

DANKE für die Arbeit, die in diesen Adapter fließt :+1:
