### ISSUE TITLE
Invalid backend error

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.vw-connect#275]
Seit zwei Tagen bekomme ich folgende Meldung im Log, es ist ein Seat Mii

{"error{"errorCode":"gw.error.unknown","description":"Invalid backend error"}}

Meine Zugangsdaten liegen dir ja vor falls du testen möchtest

**Comment by TA2k** [comment]
Bitte github version testen

**Comment by fuchs-1978** [comment]
Ist installiert, ich beobachte und berichte

**Comment by fuchs-1978** [comment]
Läuft jetzt vier Stunden ohne Fehlermeldung

**Comment by fuchs-1978** [comment]
Läuft jetzt vier Stunden ohne Fehlermeldung
