### ISSUE TITLE
"Parking position failed. Blocked until restart" mit Skoda Enyaq

### ISSUE THREAD

**Issue by michaelshgr** [TA2k/ioBroker.vw-connect#278]
iobroker-Protokoll zeigt ständig die Warnung:
Parking position failed. Blocked until restart

Objekt "vw-connect.0.<FIN>.status.positionvehicles.parking-position" nicht mehr vorhanden, seit die Github-Version installiert wurde.

vw-connect.0 | 2023-10-05 10:39:07.570 | warn | Parking position failed. Blocked until restart
vw-connect.0 | 2023-10-05 10:39:03.130 | info | Login in with skodae
vw-connect.0 | 2023-10-05 10:39:03.128 | info | Found 1 vehicles
vw-connect.0 | 2023-10-05 10:39:02.081 | info | Login successful
vw-connect.0 | 2023-10-05 10:39:00.495 | info | Login in with skodae
vw-connect.0 | 2023-10-05 10:39:00.460 | info | starting. Version 0.1.3 (non-npm: ta2k/ioBroker.vw-connect) in /opt/iobroker/node_modules/iobroker.vw-connect, node: v18.18.0, js-controller: 4.0.24

**Comment by TA2k** [comment]
Aber das sollte ja nur einmal kommen beim start.
Zum fixen bräuchte ich noch ein account 
tombox2020@gmail.com

**Comment by TA2k** [comment]
bitte mal die GitHub version testen skoda account

**Comment by michaelshgr** [comment]
Habe gerade die Version 0.1.5 installiert.
Läuft jetzt. Danke!

**Comment by schoemi** [comment]
Ich kriege es auch mit der 0.1.6 nicht gelöst.
Auch Skoda Enyaq.


```
vw-connect.1 | 2023-10-13 15:26:58.815 | warn | Parking position failed. Blocked until restart
vw-connect.1 | 2023-10-13 15:26:50.496 | info | Login in with skodae
vw-connect.1 | 2023-10-13 15:26:50.495 | info | Found 1 vehicles
vw-connect.1 | 2023-10-13 15:26:46.667 | info | Login successful
vw-connect.1 | 2023-10-13 15:26:22.676 | info | Login in with skodae
vw-connect.1 | 2023-10-13 15:26:22.660 | info | starting.  Version 0.1.6 (non-npm: ta2k/ioBroker.vw-connect) in  /opt/iobroker/node_modules/iobroker.vw-connect, node: v16.20.1,  js-controller: 4.0.24

```
Ich habe sowohl mit als auch ohne Auflösung der Parkposition und mit / ohne herunterladen der Lizenzinfo. Fahrdaten hab ich ebenfalls aktiviert / deaktiviert. 
Fehler ist reproduzierbar. 
Was mich ein wenig wundert sind die 2 protokollierten Logins (vor und nach vehicle) Oder nutzt der Adapter hier unterschiedliche Endpoints wo er sich authetifiziert?

**Comment by DerDoubleD** [comment]
Hallo.
bei mir besteht das Problem auch bei der 0.1.5 immer noch.
Wie kann ich Dir den login zukommen lassen?
![image](https://github.com/TA2k/ioBroker.vw-connect/assets/47006370/a14dec6c-e027-4641-9f61-9d82228905be)

**Comment by TA2k** [comment]
in 0.1.6 behoben
tombox2020@gmail.com

**Comment by DerDoubleD** [comment]
Jetzt kommen gar keine Positionsupdates mehr bei mir an.
Hast du den Login erhalten?

**Comment by michaelshgr** [comment]
Seit ich 0.1.6 installiert habe, kommen bei mir auch keine Updates mehr.

**Comment by TA2k** [comment]
habe noch Kein login erhalten

**Comment by DerDoubleD** [comment]
> habe noch Kein login erhalten

schau bitte nochmal. Ich habe es eben noch einmal gesendet.

**Comment by TA2k** [comment]
Fix with 0.1.9
