### ISSUE TITLE
VW Passat Lock/Unlock Error (68023) 403 failed set state

### ISSUE THREAD

**Issue by mac89muc** [TA2k/ioBroker.vw-connect#28]
Hello, not sure if this is the right board to place my problem.

I've managed to control the climatisation / flash / start window heating on my Passat GTE with the adapter. Also the lock state of the doors and windows / range / charging state etc are working.

The only thing which i could't get working is the lock / unlock function - within the original VW We Connect iOS App it works without any problem.

When I try to fire the lock/unlock Button under Objects
vw-connect.0.myFIN.remote.lock
I get the Error (68023) 403 failed set state.

My S-Pin is stored in the settings, I've also tried to delete and reinstall / start / stop the adapter.
Several engine starts between the requests haven't solved the problem either

Any tipps and tricks to find the problem and get it working or where i can place my problem if this is the false board.

Christian

 - Adapter version: <4.1.10>
 - JS-Controller version: <3.1.6> 
 - Node version: <14.15.1>
 - Operating system: <0sx>

**Comment by lainuks** [comment]
i have the same Issue with Audi

**Comment by mac89muc** [comment]
I attached the debug log in addition to my first post 5 days ago and I've got two questions

> I'm not that familiar with coding but at the end of the token line (I replaced the original Token with "langerToken") there's no quotation mark at the debug log line - is that OK, or is there a " missing?
> 
> {"securityPinAuthInfo":{"securityToken":"langerToken


> and the second question - is it ok that there's a link http://audi.de/connect/rlu shown in the debug log - because I've got a VW (I've stored that at the Adapter Preferences).

Here's the log of the Unlock command within the adapter 

Gruß
Christian

vw-connect.0 | 2020-12-10 16:28:35.887 | debug | (68792) "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><destinations/>"
-- | -- | -- | --
vw-connect.0 | 2020-12-10 16:27:39.337 | error | (68792) failed set state
vw-connect.0 | 2020-12-10 16:27:39.337 | error | (68792) 403
vw-connect.0 | 2020-12-10 16:27:39.087 | debug | (68792) application/vnd.vwg.mbb.RemoteLockUnlock_v1_0_0+xml
vw-connect.0 | 2020-12-10 16:27:39.087 | debug | </rluAction>
vw-connect.0 | 2020-12-10 16:27:39.087 | debug | <action>unlock</action>
vw-connect.0 | 2020-12-10 16:27:39.087 | debug | <rluAction xmlns="http://audi.de/connect/rlu">
vw-connect.0 | 2020-12-10 16:27:39.087 | debug | (68792) <?xml version="1.0" encoding= "UTF-8" ?>
vw-connect.0 | 2020-12-10 16:27:39.087 | debug | (68792) [object Object]
vw-connect.0 | 2020-12-10 16:27:38.627 | debug | (68792) {"securityPinAuthInfo":{"securityToken":"langerToken
vw-connect.0 | 2020-12-10 16:27:38.383 | debug | (68792) reverse pos deactivated

**Comment by TA2k** [comment]
Can you please retest

**Comment by lainuks** [comment]
it works

**Comment by mac89muc** [comment]
Thanks for your assistance and the code adaption - now it's working.
