### ISSUE TITLE
Can't get/set climatisation temperature

### ISSUE THREAD

**Issue by Docjones** [TA2k/ioBroker.vw-connect#280]
I have troubles getting or setting the climatisation temperature on my VW Passat GTE. In the new VW App I set the temperature to a certain value (eg 24 degree). The remote.climatisationTemperature endpoint is not being set. 

I can't activate climatisation by setting remote.climatisation to true. 

On the other hand I noticed that the remote.charging endpoint set to true as soon as I turn on climatisation.

**Comment by TA2k** [comment]
Delete all objects and select typ id/Volkswagen app and try again

**Comment by Docjones** [comment]
Look way better now, Thank you! 🙏 object tree is far easier to handle now..

I get "too many requests" in my log now, should wait a few hours...
