### ISSUE TITLE
Fehler im Log

### ISSUE THREAD

**Issue by MMeinhardt1** [TA2k/ioBroker.vw-connect#283]
Hi,

ich bekomme die folgenden Fehler im Log.

vw-connect.0 2023-11-19 16:28:37.689	info	No last shorterm trips found. Please check if your car supports shortterm trips.
vw-connect.0 2023-11-19 16:28:35.348	error	{"error":{"message":"Not Found","info":"Upstream service responded with an unexpected status. If the problem persists, please contact our support.","code":4112,"group":2,"retry":true}}
vw-connect.0 2023-11-19 16:28:35.347	error	No longterm trips found please disable in your settings
vw-connect.0 2023-11-19 16:28:35.347	error	AxiosError: Request failed with status code 404
vw-connect.0 2023-11-19 16:28:35.140	error	{"error":{"message":"Not Found","info":"Upstream service responded with an unexpected status. If the problem persists, please contact our support.","code":4112,"group":2,"retry":true}}
vw-connect.0 2023-11-19 16:28:35.139	error	No shortterm trips found please disable in your settings
vw-connect.0 2023-11-19 16:28:35.138	error	AxiosError: Request failed with status code 404
vw-connect.0 2023-11-19 16:28:30.337	info	Found 2 vehicles
vw-connect.0 2023-11-19 16:28:29.225	info	Login successful
vw-connect.0 2023-11-19 16:28:26.455	info	Login in with audietron
vw-connect.0 2023-11-19 16:28:26.450	info	Login in with audi as audietron
vw-connect.0 2023-11-19 16:28:26.399	info	starting. Version 0.2.5 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v18.17.1, js-controller: 5.0.16

Im meinem Audi Account sind 2 Fahrzeuge hinterlegt, ein A6 55 tfsie MJ09/21 und ein A3 30 tfsi MJ03/20.
Ich nehme an die Fehlermeldungen kommen von dem A3 da dieser auch keine Fahrdaten in der Audi App zur Verfügung stellt, aber leider lässt sich das anhand der Fehlermeldungen nicht eindeutig zuordnen.
Die auszulesenden Daten lassen sich anscheinend nicht in den Einstellungen des Adapters einstellen.

Was kann ich tun bzw. testen um den Fehler einzugrenzen?

Vielen Dank und beste Grüße
Michael

**Comment by TA2k** [comment]
du siehst ja unter welchen vin trip Daten erzeugt werden
einzige Möglichkeit ist es in den Einstellungen zu deaktivieren

**Comment by MMeinhardt1** [comment]
Wenn ich die Option deaktiviere verzichte ich aber ja bei beiden Fahrzeugen darauf, obwohl das eine die Daten liefern würde. 
Kann der Adapter eventuell so von dir umgebaut werden, dass die Fahrzeuge im ersten Schritt eingelesen werden und man danach die Möglichkeit hat zu selektieren welche Daten von welchen Fahrzeug gelesen werden sollen?

Vielen Dank und schönen Abend noch
Michael

**Comment by TA2k** [comment]
Probier mal die GitHub version ob die sich besser verhält

**Comment by MMeinhardt1** [comment]
Hier noch eine Fehlermeldung vor dem GitHub Update,

vw-connect.0 2023-11-19 19:48:15.266	info	No last shorterm trips found. Please check if your car supports shortterm trips.
vw-connect.0 2023-11-19 19:48:13.384	info	Found 2 vehicles
vw-connect.0 2023-11-19 19:48:12.289	info	Login successful
vw-connect.0 2023-11-19 19:48:08.849	info	Login in with audietron
vw-connect.0 2023-11-19 19:48:08.844	info	Login in with audi as audietron
vw-connect.0 2023-11-19 19:48:08.791	info	starting. Version 0.2.5 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v18.17.1, js-controller: 5.0.16
vw-connect.0 2023-11-19 19:48:01.111	error	Error: Could not check object existence of vw-connect.0.WAUZZZF26MNXXXXXX.shortterm.118.id: Cannot check object existence of "vw-connect.0.WAUZZZF26MNXXXXXX.shortterm.118.id": Connection is closed.
vw-connect.0 2023-11-19 19:48:01.109	error	Cannot check object existence of "vw-connect.0.WAUZZZF26MNXXXXXX.shortterm.118.id": Connection is closed.
vw-connect.0 2023-11-19 19:48:01.102	error	Error: DB closed
vw-connect.0 2023-11-19 19:48:01.101	error	Error extract keys: WAUZZZF26MNXXXXXX.shortterm.117 {"id":"1302362147","tripEndTimestamp":"2023-03-13T08:04:04Z","tripType":"shortTerm","vehicleType":"hybrid","mileage_km":16,"startMileage_km":43183,"overallMileage_km":43200,"travelTime":32,"averageFuelConsumption":0,"averageSpeed_kmph":30}
vw-connect.0 2023-11-19 19:48:01.093	info	terminating
vw-connect.0 2023-11-19 19:48:00.591	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
vw-connect.0 2023-11-19 19:48:00.588	info	terminating
vw-connect.0 2023-11-19 19:48:00.586	info	cleaned everything up...
vw-connect.0 2023-11-19 19:48:00.584	info	Got terminate signal TERMINATE_YOURSELF

Nach Installation der GutHub Version gibt es keine signifikante Änderung, die Fehlermeldungen bleiben die gleichen wie im Eingangsbeitrag. Ich habe die Trip Daten erstmal komplett deaktiviert. 

Vielen Dank
Michael

**Comment by TA2k** [comment]
Fehlermeldung sollten sich nicht ändern nur der Abruf.
