### ISSUE TITLE
Missing Objects with Type - VW ID / Volkswagen App

### ISSUE THREAD

**Issue by mac89muc** [TA2k/ioBroker.vw-connect#284]
Hello after the We Connect App shutdown I switched to Type VW ID / Volkswagen App at the Adapter settings for my Passat GTE.
The whole Datapoint Tree was rearranged so I have to adjust my scripts and recognized that I'm missing a couple of Datapoints.

e.g. Flash & Honk / just Flash / maxChargeCurrent which were placed in the Remote Tree before.
The Status of maxChargeCurrentAC exists (vw-connect.0.myFIN.status.chargingSettings.maxChargeCurrentAC) - but with the value "invalid"

Is there a chance to get them back - some of them are still visible and controllable in the new Volkswagen App.

Thanks in advance

Adapter Vers. - Git 0.2.5
js-controller 5.0.16
Node 18.18.0
NPM 9.8.1

**Comment by TA2k** [comment]
If they controllable in the app I need account where I can send it

**Comment by mac89muc** [comment]
sorry for the delayed answer - I've been in contact with the vw support. after a few vw app updates the missing functions where implemented and showing up in the tree of the vw-connect adapter.

Thanks

**Comment by mac89muc** [comment]
sorry for the delayed answer - I've been in contact with the vw support until last week. after a few vw app updates the missing functions where implemented in the new vw app and also showing up in the tree of the vw-connect adapter.

Thanks
