### ISSUE TITLE
VW Touran just works with "ID" Type.

### ISSUE THREAD

**Issue by unstressable** [TA2k/ioBroker.vw-connect#288]
I just randomly found out, that my Touran (2021) just works with the "ID" setup.
Was wondering, why the "VWv2" did not work:
<img width="185" alt="image" src="https://github.com/TA2k/ioBroker.vw-connect/assets/50423935/38759432-1618-41c8-a686-ca81a217b5df">

Maybe its because of the new "Volkswagen App"
Please rename it in the settings.

**Comment by TA2k** [comment]
Please install the latest release

**Comment by unstressable** [comment]
> Please install the latest release

if you already fixed it, thanks then.
Actually everything seem to work with the "ID" Type.

**Comment by unstressable** [comment]
latest github version fixed that. Thanks.
