### ISSUE TITLE
Keine Reichweite mehr seit 08.12.2020

### ISSUE THREAD

**Issue by mhoerche** [TA2k/ioBroker.vw-connect#29]
Seit diesem Datum wird die Reichweite für meinen eUp nicht mehr aktualisiert.
/status/data6/field5

**Comment by mac89muc** [comment]
Findet sich bei mir jetzt in den Objekten unter - vw-connect.0.deineFIN.charger.status.cruisingRangeStatusData
Darunter gibt es die Reichweite für Hybrid / primaryEngine / secondaryEngine.

Gruß

**Comment by mhoerche** [comment]
Danke!

**Comment by mhoerche** [comment]
Funktioniert :-)
