### ISSUE TITLE
Error in OnStateChange: TypeError: state.val.toLocaleLowerCase is not a function

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.vw-connect#292]
Nach dem Update von 0.2.5 auf 0.3.0 bekomme ich regelmäßig den Fehler:

Error in OnStateChange: TypeError: state.val.toLocaleLowerCase is not a function

<html>
<body>

vw-connect.0 | 2023-12-04 06:14:14.259 | error | Error in OnStateChange: TypeError: state.val.toLocaleLowerCase is not a function
vw-connect.0 | 2023-12-04 05:59:18.758 | error | Error in OnStateChange: TypeError: state.val.toLocaleLowerCase is not a function
vw-connect.0 | 2023-12-04 05:59:16.765 | error | Error in OnStateChange: TypeError: state.val.toLocaleLowerCase is not a function

</body>
</html>

Nach einem Downgrade ist die Meldung verschwunden.

**Comment by TA2k** [comment]
Danke für den Hinweis. Bitte 0.3.2 testen
