### ISSUE TITLE
ID.3 could not set charging state

### ISSUE THREAD

**Issue by obiwan007** [TA2k/ioBroker.vw-connect#30]
**Describe the bug**  
If I just set the remote/chargin to false, the new state will not be issued to the car.
The errormessage is
`{"error":{"code":2104,"message":"The user has no relation with the VIN","group":1,"info":"Car is not enrolled anymore."}}`

I get all the current states like SOC, plug state etc...

**Expected behavior**  
Charging needs to bes stopped/Started

**Versions:**  
 - Adapter version: 0.0.21
- Version of Car SW 0564

**Comment by TiDO2k** [comment]
@obiwan007 
please delete the complete adapter in iobroker and reinstall version 0.0.22
This worked for me! Now everything is running.
