### ISSUE TITLE
Kann Instanz nicht unter node 12 starten

### ISSUE THREAD

**Issue by ivosch68** [TA2k/ioBroker.vw-connect#31]
Mit node 12 kann die Instanz nicht gestartet werden. Mit node 10 funktioniert es.

**Comment by TA2k** [comment]
Bitte Anweisung zum Update von nodejs befolgen
https://forum.iobroker.net/topic/22867/how-to-node-js-für-iobroker-richtig-updaten

cd /opt/iobroker
npm install canvas
npm rebuild
