### ISSUE TITLE
Reihenfolge der Tripdaten "Longterm"

### ISSUE THREAD

**Issue by fL4sH3r** [TA2k/ioBroker.vw-connect#314]
Bei der Reihenfolge der Tripdaten ist es so, dass die aktuellsten Werte theoretisch immer im Ordner 01 sind/waren. Bei Shortterm (Kurzstrecke) und Cyclic (Laden) funktioniert das auch Prima. Bei Longterm (Langstrecke) werden die Werte in der falschen Reihenfolge abgespeichert.
Es wäre schön wenn die aktuellsten Werte immer im ersten Ordner wären.

![image](https://github.com/TA2k/ioBroker.vw-connect/assets/97987283/e1290136-e82c-4945-80af-8650b3b9a995)

Hier ein Beispiel von cyclic, longterm und shortterm.
![image](https://github.com/TA2k/ioBroker.vw-connect/assets/97987283/8244f443-e64f-4393-968c-ba3c1d70809b)

**Comment by TA2k** [comment]
eigentlich wird longterm auch nach id sortiert kannst du bitte die id checken

**Comment by fL4sH3r** [comment]
hier die ID
![image](https://github.com/TA2k/ioBroker.vw-connect/assets/97987283/17fb836b-8bdf-4a76-9b38-d33352f12db6)

**Comment by fL4sH3r** [comment]
Perfekt, funktioniert. 

Danke dir.
