### ISSUE TITLE
Audi etron No data

### ISSUE THREAD

**Issue by heiko73** [TA2k/ioBroker.vw-connect#315]
**Describe the bug**  
vwconnect instance is correctly finding my vehicle (Audi etron 2020 model) and shows some data like parking position. There are no datapoints created under status at all

**To Reproduce**  
1. Buy an Audi etron (OK, just kidding, no idea how to reproduce this for someone else)

**Expected behavior**  
I would expect at least a few basic datapoints like State of Charge or remaining range etc. under "status". 

**Screenshots & Logfiles**  
Not required, I assume. Please let me know if otherwise

**Versions:**  
 - Adapter version: 0.0.67
 - JS-Controller version: 5.0.17
 - Node version: 20.10.0
 - Operating system: Linux (Docker)

Thank you for any recommendation/advise here, and thanks overall for providing this adapter!

**Comment by TA2k** [comment]
please use 0.5.1

**Comment by heiko73** [comment]
0.5.1 works like a charm - vielen Dank!

**Comment by Kitz252** [comment]
Hallo, ich habs leider noch nicht überrissen was die Lösung ist. Ich habe das selbe Problem wie @heiko73.
von was soll ich die Version 0.5.1 verwenden. Vom Adapter selbst ist ja die 0.0.67 die aktuellste oder?
