### ISSUE TITLE
Error in Version 25 with Seat Mii

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.vw-connect#34]
Mit Version 25 bekomme ich folgende Fehlermeldung bei Seat Mii. Zurück auf Version 23 verschwindet der Fehler.

vw-connect.0 | 2021-01-22 07:39:23.174 | error | (28153) Failed relogin
-- | -- | -- | --
vw-connect.0 | 2021-01-22 07:39:23.173 | error | (28153) Error: Invalid protocol: seatconnect:
vw-connect.0 | 2021-01-22 07:39:23.173 | error | (28153) Failed in first login step
vw-connect.0 | 2021-01-22 07:39:21.564 | error | (28153) Relogin
vw-connect.0 | 2021-01-22 07:39:21.564 | error | (28153) 400
vw-connect.0 | 2021-01-22 07:39:21.564 | error | (28153) {"errorCode":"REQUEST_DATA_INVALID","description":"invalid brand or token audience"}
vw-connect.0 | 2021-01-22 07:39:21.564 | error | (28153)
vw-connect.0 | 2021-01-22 07:39:21.563 | error | (28153) Failing to refresh token.
vw-connect.0 | 2021-01-22 06:45:22.993 | error | (28153) Failed relogin
vw-connect.0 | 2021-01-22 06:45:22.992 | error | (28153) Error: Invalid protocol: seatconnect:
vw-connect.0 | 2021-01-22 06:45:22.992 | error | (28153) Failed in first login step
vw-connect.0 | 2021-01-22 06:45:21.492 | error | (28153) Relogin
vw-connect.0 | 2021-01-22 06:45:21.492 | error | (28153) 400
vw-connect.0 | 2021-01-22 06:45:21.492 | error | (28153) {"errorCode":"REQUEST_DATA_INVALID","description":"invalid brand or token audience"}
vw-connect.0 | 2021-01-22 06:45:21.492 | error | (28153)
vw-connect.0 | 2021-01-22 06:45:21.491 | error | (28153) Failing to refresh token.

**Comment by TA2k** [comment]
I need the full log please send via iobroker forum

**Comment by TA2k** [comment]
Please reinstall via github

**Comment by fuchs-1978** [comment]
Ich habe den Adapter nochmal aus dem Github installiert. Fehler bleibt bestehen:


vw-connect.0 | 2021-01-28 15:09:07.849 | error | (4297) Relogin
-- | -- | -- | --
vw-connect.0 | 2021-01-28 15:09:07.849 | error | (4297) 400
vw-connect.0 | 2021-01-28 15:09:07.849 | error | (4297) {"error":"invalid_grant","error_description":"Signature of id token (or refresh token) is invalid or token is expired"}
vw-connect.0 | 2021-01-28 15:09:07.849 | error | (4297) VwToken
vw-connect.0 | 2021-01-28 15:09:07.849 | error | (4297) Failing to refresh token.
vw-connect.0 | 2021-01-28 15:09:07.780 | error | (4297) Relogin
vw-connect.0 | 2021-01-28 15:09:07.780 | error | (4297) 400
vw-connect.0 | 2021-01-28 15:09:07.780 | error | (4297) {"message":"Required String parameter 'grant_type' is not present"}
vw-connect.0 | 2021-01-28 15:09:07.780 | error | (4297)
vw-connect.0 | 2021-01-28 15:09:07.780 | error | (4297) Failing to refresh token.
vw-connect.0 | 2021-01-28 15:09:07.766 | error | (4297) Relogin
vw-connect.0 | 2021-01-28 15:09:07.766 | error | (4297) 400
vw-connect.0 | 2021-01-28 15:09:07.766 | error | (4297) {"message":"Required String parameter 'grant_type' is not present"}
vw-connect.0 | 2021-01-28 15:09:07.766 | error | (4297)
vw-connect.0 | 2021-01-28 15:09:07.766 | error | (4297) Failing to refresh token.
vw-connect.0 | 2021-01-28 15:09:05.692 | error | (4297) Relogin
vw-connect.0 | 2021-01-28 15:09:05.692 | error | (4297) 400

**Comment by TA2k** [comment]
fixed
