### ISSUE TITLE
Limit number of states

### ISSUE THREAD

**Issue by FChristian** [TA2k/ioBroker.vw-connect#4]
Hey guys,
the adapter is really cool, thank you for your work.
BUT: the number of states is absolutely killing the ioBroker performance. Within shortest time of having the adapter installed and running (we're talking about hours), it created more than 11.000 states and this killed the database performance, following an almost complete hung up ioBroker installation. And: this installation is hosted on an Intel N3150 CPU with 8GB RAM, not on a Raspi!

Even the uninstallation took 15 minutes!

Possible reason could be: make the transmission of the recent navigation target data optional, so this would not transfer all the rides since I have bought the car ;) This is creating a enormous data amount. Maybe another option in the selection "short term, long term, both" would be "none" ;)

Thank you!

PS: this is the uninstall log..

> 2020-01-23 21:54:23.221 - info: host.iobroker iobroker del vw-connect.0
> 2020-01-23 21:54:26.958 - info: host.iobroker iobroker Delete adapter "vw-connect.0"
> 2020-01-23 21:54:27.297 - info: host.iobroker iobroker host.iobroker Counted 1 instances of vw-connect.0
> 2020-01-23 21:54:27.371 - info: host.iobroker iobroker host.iobroker Counted 1 devices of vw-connect.0
> 2020-01-23 21:54:27.439 - info: host.iobroker iobroker host.iobroker Counted 1 channels of vw-connect.0
> 2020-01-23 21:54:28.845 - info: host.iobroker iobroker host.iobroker Counted 11545 states of vw-connect.0
> 2020-01-23 21:54:29.285 - info: host.iobroker iobroker host.iobroker Counted 14 states of system.adapter.vw-connect.0
> 2020-01-23 21:54:38.139 - info: host.iobroker iobroker host.iobroker Deleting 11562 object(s). Be patient...
> 2020-01-23 21:54:50.641 - info: host.iobroker iobroker host.iobroker: Only 11400 objects left to be deleted.
> 2020-01-23 21:55:06.780 - info: host.iobroker iobroker host.iobroker: Only 11200 objects left to be deleted.
> 2020-01-23 21:55:24.623 - info: host.iobroker iobroker host.iobroker: Only 11000 objects left to be deleted.
> 2020-01-23 21:55:39.646 - info: host.iobroker iobroker host.iobroker: Only 10800 objects left to be deleted.
> 2020-01-23 21:55:56.709 - info: host.iobroker iobroker host.iobroker: Only 10600 objects left to be deleted.
> 2020-01-23 21:56:12.294 - info: host.iobroker iobroker host.iobroker: Only 10400 objects left to be deleted.
> 2020-01-23 21:56:29.489 - info: host.iobroker iobroker host.iobroker: Only 10200 objects left to be deleted.
> 2020-01-23 21:56:45.145 - info: host.iobroker iobroker host.iobroker: Only 10000 objects left to be deleted.
> 2020-01-23 21:57:00.198 - info: host.iobroker iobroker host.iobroker: Only 9800 objects left to be deleted.
> 2020-01-23 21:57:15.259 - info: host.iobroker iobroker host.iobroker: Only 9600 objects left to be deleted.
> 2020-01-23 21:57:30.604 - info: host.iobroker iobroker host.iobroker: Only 9400 objects left to be deleted.
> 2020-01-23 21:57:46.018 - info: host.iobroker iobroker host.iobroker: Only 9200 objects left to be deleted.
> 2020-01-23 21:58:00.616 - info: host.iobroker iobroker host.iobroker: Only 9000 objects left to be deleted.
> 2020-01-23 21:58:15.714 - info: host.iobroker iobroker host.iobroker: Only 8800 objects left to be deleted.
> 2020-01-23 21:58:30.812 - info: host.iobroker iobroker host.iobroker: Only 8600 objects left to be deleted.
> 2020-01-23 21:58:46.743 - info: host.iobroker iobroker host.iobroker: Only 8400 objects left to be deleted.
> 2020-01-23 21:59:01.516 - info: host.iobroker iobroker host.iobroker: Only 8200 objects left to be deleted.
> 2020-01-23 21:59:16.643 - info: host.iobroker iobroker host.iobroker: Only 8000 objects left to be deleted.
> 2020-01-23 21:59:31.351 - info: host.iobroker iobroker host.iobroker: Only 7800 objects left to be deleted.
> 2020-01-23 21:59:46.549 - info: host.iobroker iobroker host.iobroker: Only 7600 objects left to be deleted.
> 2020-01-23 22:00:03.815 - info: host.iobroker iobroker host.iobroker: Only 7400 objects left to be deleted.
> 2020-01-23 22:00:30.707 - info: host.iobroker iobroker host.iobroker: Only 7200 objects left to be deleted.
> 2020-01-23 22:00:44.611 - info: host.iobroker iobroker host.iobroker: Only 7000 objects left to be deleted.
> 2020-01-23 22:01:01.162 - info: host.iobroker iobroker host.iobroker: Only 6800 objects left to be deleted.
> 2020-01-23 22:01:17.359 - info: host.iobroker iobroker host.iobroker: Only 6600 objects left to be deleted.
> 2020-01-23 22:01:35.311 - info: host.iobroker iobroker host.iobroker: Only 6400 objects left to be deleted.
> 2020-01-23 22:01:52.330 - info: host.iobroker iobroker host.iobroker: Only 6200 objects left to be deleted.
> 2020-01-23 22:02:08.895 - info: host.iobroker iobroker host.iobroker: Only 6000 objects left to be deleted.
> 2020-01-23 22:02:24.930 - info: host.iobroker iobroker host.iobroker: Only 5800 objects left to be deleted.
> 2020-01-23 22:02:40.447 - info: host.iobroker iobroker host.iobroker: Only 5600 objects left to be deleted.
> 2020-01-23 22:02:55.769 - info: host.iobroker iobroker host.iobroker: Only 5400 objects left to be deleted.
> 2020-01-23 22:03:11.334 - info: host.iobroker iobroker host.iobroker: Only 5200 objects left to be deleted.
> 2020-01-23 22:03:26.339 - info: host.iobroker iobroker host.iobroker: Only 5000 objects left to be deleted.
> 2020-01-23 22:03:42.507 - info: host.iobroker iobroker host.iobroker: Only 4800 objects left to be deleted.
> 2020-01-23 22:03:58.467 - info: host.iobroker iobroker host.iobroker: Only 4600 objects left to be deleted.
> 2020-01-23 22:04:13.239 - info: host.iobroker iobroker host.iobroker: Only 4400 objects left to be deleted.
> 2020-01-23 22:04:30.081 - info: host.iobroker iobroker host.iobroker: Only 4200 objects left to be deleted.
> 2020-01-23 22:04:46.301 - info: host.iobroker iobroker host.iobroker: Only 4000 objects left to be deleted.
> 2020-01-23 22:05:03.952 - info: host.iobroker iobroker host.iobroker: Only 3800 objects left to be deleted.
> 2020-01-23 22:05:21.536 - info: host.iobroker iobroker host.iobroker: Only 3600 objects left to be deleted.
> 2020-01-23 22:05:53.430 - info: host.iobroker iobroker host.iobroker: Only 3200 objects left to be deleted.
> 2020-01-23 22:06:08.086 - info: host.iobroker iobroker host.iobroker: Only 3000 objects left to be deleted.
> 2020-01-23 22:06:22.451 - info: host.iobroker iobroker host.iobroker: Only 2800 objects left to be deleted.
> 2020-01-23 22:06:36.411 - info: host.iobroker iobroker host.iobroker: Only 2600 objects left to be deleted.
> 2020-01-23 22:06:50.688 - info: host.iobroker iobroker host.iobroker: Only 2400 objects left to be deleted.
> 2020-01-23 22:07:04.727 - info: host.iobroker iobroker host.iobroker: Only 2200 objects left to be deleted.
> 2020-01-23 22:07:18.052 - info: host.iobroker iobroker host.iobroker: Only 2000 objects left to be deleted.
> 2020-01-23 22:07:32.862 - info: host.iobroker iobroker host.iobroker: Only 1800 objects left to be deleted.
> 2020-01-23 22:07:45.961 - info: host.iobroker iobroker host.iobroker: Only 1600 objects left to be deleted.
> 2020-01-23 22:08:00.070 - info: host.iobroker iobroker host.iobroker: Only 1400 objects left to be deleted.
> 2020-01-23 22:08:14.239 - info: host.iobroker iobroker host.iobroker: Only 1200 objects left to be deleted.
> 2020-01-23 22:08:28.109 - info: host.iobroker iobroker host.iobroker: Only 1000 objects left to be deleted.
> 2020-01-23 22:08:42.281 - info: host.iobroker iobroker host.iobroker: Only 800 objects left to be deleted.
> 2020-01-23 22:08:56.103 - info: host.iobroker iobroker host.iobroker: Only 600 objects left to be deleted.
> 2020-01-23 22:09:10.494 - info: host.iobroker iobroker host.iobroker: Only 400 objects left to be deleted.
> 2020-01-23 22:09:24.081 - info: host.iobroker iobroker host.iobroker: Only 200 objects left to be deleted.
> 2020-01-23 22:09:38.022 - info: host.iobroker object deleted system.adapter.vw-connect.0

**Comment by TA2k** [comment]
fixed with v0.0.9
