### ISSUE TITLE
several JS error

### ISSUE THREAD

**Issue by FChristian** [TA2k/ioBroker.vw-connect#5]
Hi, thank you for closing the "lastposition" issue #4 that fast, really exciting! I just decided to re-do a test installation, it works, but puts out several JS errors, see below. Additional (very minor) case: the 0.0.9 shows up in the repo as 0.0.9, but in the log it prints 0.0.8 (see also below).

> vw-connect.0	2020-01-25 22:25:10.961	error	(17001) 502
vw-connect.0	2020-01-25 22:25:10.893	error	(17001) 400
vw-connect.0	2020-01-25 22:25:04.852	info	(17001) starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v10.18.0
host.iobroker	2020-01-25 22:24:58.842	info	instance system.adapter.vw-connect.0 started with pid 17001
host.iobroker	2020-01-25 22:24:56.843	info	instance system.adapter.vw-connect.0 terminated with code 156 (156)
vw-connect.0	2020-01-25 22:24:56.263	info	(15988) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
vw-connect.0	2020-01-25 22:24:56.261	info	(15988) terminating
vw-connect.0	2020-01-25 22:24:56.260	info	(15988) cleaned everything up...
vw-connect.0	2020-01-25 22:24:56.258	info	(15988) Got terminate signal TERMINATE_YOURSELF
host.iobroker	2020-01-25 22:24:56.249	info	stopInstance system.adapter.vw-connect.0 send kill signal
host.iobroker	2020-01-25 22:24:56.247	info	stopInstance system.adapter.vw-connect.0 (force=false, process=true)
vw-connect.0	2020-01-25 22:24:24.351	error	at process._tickCallback (internal/process/next_tick.js:63:19)
vw-connect.0	2020-01-25 22:24:24.351	error	at endReadableNT (_stream_readable.js:1143:12)
vw-connect.0	2020-01-25 22:24:24.351	error	at IncomingMessage.emit (events.js:203:15)
vw-connect.0	2020-01-25 22:24:24.351	error	at Object.onceWrapper (events.js:286:20)
vw-connect.0	2020-01-25 22:24:24.351	error	at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
vw-connect.0	2020-01-25 22:24:24.351	error	at Request.emit (events.js:198:13)
vw-connect.0	2020-01-25 22:24:24.351	error	at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
vw-connect.0	2020-01-25 22:24:24.351	error	at Request.emit (events.js:198:13)
vw-connect.0	2020-01-25 22:24:24.351	error	at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
vw-connect.0	2020-01-25 22:24:24.351	error	at Request.request.post [as _callback] (/opt/iobroker/node_modules/iobroker.vw-connect/main.js:341:75)
vw-connect.0	2020-01-25 22:24:24.351	error	(15988) TypeError: Cannot read property 'split' of undefined
vw-connect.0	2020-01-25 22:24:24.348	error	(15988) TypeError: Cannot read property 'split' of undefined
vw-connect.0	2020-01-25 22:24:24.345	error	(15988) 403
vw-connect.0	2020-01-25 22:24:24.079	error	(15988) No Login Form found
vw-connect.0	2020-01-25 22:24:21.294	info	(15988) starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v10.18.0

**Comment by TA2k** [comment]
this looks like a wrong email address i fixed the long error and the version this in the 0.0.10
