### ISSUE TITLE
Aktualisierung Kurzeit Daten

### ISSUE THREAD

**Issue by AUTTEC-MK** [TA2k/ioBroker.vw-connect#58]
Seit dem Update heute Funktioniert das Auslesen der Kurzeitdaten nicht mehr. Es kann im Menü nur noch "Langzeitdaten, ab Start, ab Tanken und keine" ausgewählt werden. 
Installierte Version 0.0.29
Fahrzeug: Audi e-tron Baujahr 10/2020

Im Fahrzeug habe ich auch nur Kurzzeitdaten und Langzeitdaten wie es vor dem Update ausgewählt werden konnte.

**Comment by TA2k** [comment]
Ab Start sind die Kurzzeit daten ich werde die Anpassungen nochmal korrigieren

**Comment by AUTTEC-MK** [comment]
OK
Noch zur Info. 
Dies war nach dem update auch eingestellt. Es wurde ein neuer Ordner "tripdatashortTerm" erstellt. In diesem liegen Daten von Oct20. Der bestehende Ordner "tripdata" wurde seit dem update nicht mehr aktualisiert.
