### ISSUE TITLE
ID.3: (2254) force status update Failed

### ISSUE THREAD

**Issue by Borilu** [TA2k/ioBroker.vw-connect#64]
I receive often the following error in the log:
vw-connect.0 | 2021-03-02 06:43:14.804 | error | (2254) force status update Failed
vw-connect.0 | 2021-03-02 06:43:14.804 | error | (2254) Error: Invalid URI "undefined/fs-car/bs/vsr/v1/Wc/DE/vehicles/WVWZZZ****/requests"
vw-connect.0 | 2021-03-02 06:43:14.797 | error | (2254) WVWZZZ****

**Comment by TA2k** [comment]
You can put 0 as force update in the instance settings or install the version via github then this error is gone
