### ISSUE TITLE
The adapter does not work on my ioBroker installation

### ISSUE THREAD

**Issue by ingiz71** [TA2k/ioBroker.vw-connect#65]
I tested with the Versions 0.0.29 and 0.0.30. Both have the same problem. The instance does not start at all. No connection to the host is possible. Please have a look into the attached screenshot. What can be the reason for this behavior?
![instance](https://user-images.githubusercontent.com/59662851/109725302-398e7f80-7bb1-11eb-9b03-1471793fac66.jpg)
![log](https://user-images.githubusercontent.com/59662851/109725304-3abfac80-7bb1-11eb-9bfe-940a46c3a35f.jpg)
![adapter settings](https://user-images.githubusercontent.com/59662851/109725308-3bf0d980-7bb1-11eb-9307-cd613c6d7209.jpg)
![system information](https://user-images.githubusercontent.com/59662851/109725311-3bf0d980-7bb1-11eb-9f79-ec68b9a20470.jpg)

**Comment by TA2k** [comment]
Problem after nodejs update
cd /opt/iobroker
npm install canvas

**Comment by ingiz71** [comment]
Thx! This solved the issue. Everything works now as expected. Great job!
