### ISSUE TITLE
Support for NodeJS 12

### ISSUE THREAD

**Issue by mdietz666** [TA2k/ioBroker.vw-connect#69]
Please add support for NodeJS v12

**Comment by TA2k** [comment]
is supported https://github.com/TA2k/ioBroker.vw-connect/actions/runs/653235369

**Comment by Guenda85** [comment]
it used to work before i updated to NodeJS; i just tried a full re-install of the adapter:

$ ./iobroker url "https://github.com/TA2k/ioBroker.vw-connect"
install TA2k/ioBroker.vw-connect#4e769bd5efeb788ef062fff4127e4219ee1474a4
NPM version: 7.6.3npm install TA2k/ioBroker.vw-connect#4e769bd5efeb788ef062fff4127e4219ee1474a4 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! must provide realpath for Link node

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-03-23T06_18_21_607Z-debug.log
ERROR: host.gke-sv-web Cannot install TA2k/ioBroker.vw-connect#4e769bd5efeb788ef062fff4127e4219ee1474a4: 1
ERROR: process exited with code 25

content of logfile:
/home/iobroker/.npm/_logs$ cat 2021-03-23T06_18_21_607Z-debug.log
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'TA2k/ioBroker.vw-connect#4e769bd5efeb788ef062fff4127e4219ee1474a4',
0 verbose cli   '--loglevel',
0 verbose cli   'error',
0 verbose cli   '--prefix',
0 verbose cli   '/opt/iobroker'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v14.16.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/opt/iobroker/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/opt/iobroker/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 6fe1537c5ff670d5
20 timing npm:load Completed in 10ms
21 timing arborist:ctor Completed in 0ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 1577ms
24 http fetch GET 200 https://codeload.github.com/TA2k/ioBroker.vw-connect/tar.gz/4e769bd5efeb788ef062fff4127e4219ee1474a4 1166ms
25 timing idealTree:userRequests Completed in 1225ms
26 silly idealTree buildDeps
27 silly fetch manifest iobroker.spotify-premium@https://github.com/twonky4/ioBroker.spotify-premium/tarball/4f992c01ecf6998948079f6d4bdab68052974ddc
28 http fetch GET 304 https://codeload.github.com/iobroker-community-adapters/ioBroker.spotify-premium/legacy.tar.gz/4f992c01ecf6998948079f6d4bdab68052974ddc 268ms (from cache)
29 silly fetch manifest iobroker.vuplus@https://github.com/vader722/ioBroker.vuplus/tarball/dcbdb2ad24c10f49a67ee6d699980650744a9b48
30 http fetch GET 304 https://codeload.github.com/vader722/ioBroker.vuplus/legacy.tar.gz/dcbdb2ad24c10f49a67ee6d699980650744a9b48 205ms (from cache)
31 silly fetch manifest iobroker.vw-carnet@https://github.com/RPerkuhn/ioBroker.vw-carnet/tarball/b5ccc4534509d212fb3237ea6f8a7a4114bef062
32 http fetch GET 304 https://codeload.github.com/RPerkuhn/ioBroker.vw-carnet/legacy.tar.gz/b5ccc4534509d212fb3237ea6f8a7a4114bef062 193ms (from cache)
33 silly fetch manifest iobroker.vw-connect@TA2k/ioBroker.vw-connect#4e769bd5efeb788ef062fff4127e4219ee1474a4
34 http fetch GET 304 https://codeload.github.com/TA2k/ioBroker.vw-connect/tar.gz/4e769bd5efeb788ef062fff4127e4219ee1474a4 168ms (from cache)
35 silly placeDep ROOT iobroker.objects-redis@ REPLACE for: iobroker.inst@1.1.2 want: file:node_modules/iobroker.objects-redis
36 timing idealTree Completed in 3758ms
37 timing command:install Completed in 3761ms
38 verbose stack TypeError: must provide realpath for Link node
38 verbose stack     at new Link (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/link.js:15:13)
38 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1284:20)
38 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:851:46
38 verbose stack     at Array.map (<anonymous>)
38 verbose stack     at Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:851:8)
38 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
38 verbose stack     at async Promise.all (index 1)
38 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
38 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:120:5)
39 verbose cwd /opt/iobroker
40 verbose Linux 4.15.0-139-generic
41 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "TA2k/ioBroker.vw-connect#4e769bd5efeb788ef062fff4127e4219ee1474a4" "--loglevel" "error" "--prefix" "/opt/iobroker"
42 verbose node v14.16.0
43 verbose npm  v7.6.3
44 error must provide realpath for Link node
45 verbose exit 1

**Comment by TA2k** [comment]
Did you try to reinstall via admin webinterface?

**Comment by Guenda85** [comment]
actuall it turned out that it was related to misconfiguration of nodejs and npm etc...

Am 23.03.2021 um 19:37 schrieb TA2k ***@***.******@***.***>>:



Did you try to reinstall via admin webinterface?

**Comment by MarcelW85** [comment]
`

host.raspberrypi | 2021-03-26 16:32:27.904 | info | Rebuild for adapter system.adapter.vw-connect.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.raspberrypi | 2021-03-26 16:32:27.903 | error | instance system.adapter.vw-connect.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2021-03-26 16:32:27.903 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.raspberrypi | 2021-03-26 16:32:27.903 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.raspberrypi | 2021-03-26 16:32:27.903 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.raspberrypi | 2021-03-26 16:32:27.902 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.raspberrypi | 2021-03-26 16:32:27.902 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
host.raspberrypi | 2021-03-26 16:32:27.902 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
host.raspberrypi | 2021-03-26 16:32:27.902 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)
host.raspberrypi | 2021-03-26 16:32:27.902 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.raspberrypi | 2021-03-26 16:32:27.901 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.raspberrypi | 2021-03-26 16:32:27.901 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
host.raspberrypi | 2021-03-26 16:32:27.901 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.raspberrypi | 2021-03-26 16:32:27.901 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
host.raspberrypi | 2021-03-26 16:32:27.901 | error | Caught by controller[0]: NODE_MODULE_VERSION 64. This version of Node.js requires
host.raspberrypi | 2021-03-26 16:32:27.901 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.raspberrypi | 2021-03-26 16:32:27.900 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
host.raspberrypi | 2021-03-26 16:32:27.900 | error | Caught by controller[0]: ^
host.raspberrypi | 2021-03-26 16:32:27.900 | error | Caught by controller[0]: return process.dlopen(module, path.toNamespacedPath(filename));
host.raspberrypi | 2021-03-26 16:32:27.900 | error | Caught by controller[0]: internal/modules/cjs/loader.js:1057

`

NodeJS 12.21.0

Gibt es schon eine Lösung für das Problem?

**Comment by stevie77** [comment]
I tried to install and reinstall (after seeing failures in log file) this VW adapter several times, last time with actual version Node.js v12.22.1, but I always get following problems with Node.js.

`host.iobroker	2021-05-06 00:01:33.446	error	instance system.adapter.vw-connect.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker	2021-05-06 00:01:33.446	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker	2021-05-06 00:01:33.446	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker	2021-05-06 00:01:33.446	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker	2021-05-06 00:01:33.446	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.iobroker	2021-05-06 00:01:33.445	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
host.iobroker	2021-05-06 00:01:33.445	error	Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
host.iobroker	2021-05-06 00:01:33.445	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)
host.iobroker	2021-05-06 00:01:33.445	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker	2021-05-06 00:01:33.445	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker	2021-05-06 00:01:33.445	error	Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
host.iobroker	2021-05-06 00:01:33.444	error	Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.iobroker	2021-05-06 00:01:33.444	error	Caught by controller[0]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
host.iobroker	2021-05-06 00:01:33.444	error	Caught by controller[0]: NODE_MODULE_VERSION 64. This version of Node.js requires
host.iobroker	2021-05-06 00:01:33.444	error	Caught by controller[0]: was compiled against a different Node.js version using
host.iobroker	2021-05-06 00:01:33.444	error	Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
host.iobroker	2021-05-06 00:01:33.444	error	Caught by controller[0]: ^
host.iobroker	2021-05-06 00:01:33.443	error	Caught by controller[0]: return process.dlopen(module, path.toNamespacedPath(filename));
host.iobroker	2021-05-06 00:01:33.443	error	Caught by controller[0]: internal/modules/cjs/loader.js:1057
host.iobroker	2021-05-06 00:01:31.640	info	instance system.adapter.vw-connect.0 started with pid 1779
host.iobroker	2021-05-06 00:01:31.480	info	iobroker npm-rebuild: exit 0
host.iobroker	2021-05-06 00:01:30.360	info	iobroker npm-rebuild: Rebuild vw-connect done
host.iobroker	2021-05-06 00:01:30.358	info	iobroker npm-rebuild:`

It looks like the adapter was compiled against an older version of Node.js? Is there a plan to release a version with actual Node.js v12? Or is it possible, that something other is wrong with my installation attempt? I tried to install using the Admin web UI...

**Comment by TA2k** [comment]
cd /opt/iobroker
npm install canvas

**Comment by stevie77** [comment]
That solved my problem, great. Thank you very much!
