### ISSUE TITLE
Support for ID Charger Pro?

### ISSUE THREAD

**Issue by jhartlep** [TA2k/ioBroker.vw-connect#72]
Hey,
does your adapter support the ID Charger Pro?
If not, could you add support for this charger?

**Comment by TA2k** [comment]
What is the different to weCharge?

**Comment by nightsha-de** [comment]
There is no difference. You'll find the charger under wecharge/homecharging.

**Comment by jhartlep** [comment]
Ok, but what TYPE do I need to set?
If I set Type in the configuration to ID, I get the following error in the log:


vw-connect.0 | 2021-03-25 07:16:42.979 | warn | (16355) Failled wall charger login
vw-connect.0 | 2021-03-25 07:16:42.978 | error | (16355) No Login Form found
vw-connect.0 | 2021-03-25 07:16:38.822 | info | (16355) starting. Version 0.0.30 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v12.21.0, js-controller: 3.2.16

Type VW gives:


vw-connect.0 | 2021-03-25 07:18:39.984 | error | (16409) Get Vehicles Failed
-- | -- | -- | --
vw-connect.0 | 2021-03-25 07:18:39.984 | error | (16409) Not able to find vehicle, did you choose the correct type in the settings?
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Gunzip.emit (events.js:326:22)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Object.onceWrapper (events.js:420:28)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Gunzip.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request.EventEmitter.emit (domain.js:483:12)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request.emit (events.js:314:20)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request.EventEmitter.emit (domain.js:483:12)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request.emit (events.js:314:20)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.vw-connect/main.js:1263:60)
vw-connect.0 | 2021-03-25 07:18:39.984 | error | (16409) TypeError: Cannot read property 'vehicle' of null
vw-connect.0 | 2021-03-25 07:18:39.982 | error | (16409) TypeError: Cannot read property 'vehicle' of null
vw-connect.0 | 2021-03-25 07:18:36.624 | info | (16409) starting. Version 0.0.30 in /opt/iobroker/node_modules/iobroker.vw-connect, node: v12.21.0, js-controller: 3.2.16

**Comment by andig** [comment]
Imho this plugin if for the *vehicle* integration, your question is about *charger* integration. Totally different things?

**Comment by nightsha-de** [comment]
Type "id" should be correct. Have you tried logging in on the web site? I remember some problems when VW changed the TOU and presented a disclaimer. This broke the login for the plugin until you acknowledged the disclaimer on the web.

**Comment by jhartlep** [comment]
@nightsha-de 
Which of the many websites of the vw-group do you mean?
