### ISSUE TITLE
2 Audi in 1 Audi connect, but "general" is interchanged

### ISSUE THREAD

**Issue by maverickmu** [TA2k/ioBroker.vw-connect#8]
I've added a second Audi A3 to my Audi connect. 

It will be recognised, but now the whole "general" under iobroker/objects is interchanged. So my A5 is now an A3 and the other way around. Also the links to the images are changed.

I tried to uninstall and make a fresh install without luck. Maybe some have the same behavior and a solution? If you need anything to help, let me know.
Thanks

**Versions:**  
 - Adapter version: 0.0.10
 - JS-Controller version: 10.18.1
 - Node version: 13.6.0
 - Operating system: raspbian

**Comment by TA2k** [comment]
Mh is for me tough to fix this without an account
can you please contact me in the iobroker forum 
https://forum.iobroker.net/user/tombox
Three dots on the side start chat

**Comment by TA2k** [comment]
Can you please send me your debug log via mail?

**Comment by TA2k** [comment]
should fix in 0.0.11
