### ISSUE TITLE
Connection state not set to false on shutdown

### ISSUE THREAD

**Issue by tillsteinbach** [TA2k/ioBroker.vw-connect#85]
**Describe the bug**  
be-connect.\d+.info.connection is not set to false on shutdown.

I make use of this state to indicate to my HomeKit devices that the connection is down. Unfortunately it is never set to false on shutdown.

**To Reproduce**  
1. Setup adapter 
2. Enable adapter
3. Disable adapter
4. Check state.

**Expected behavior**  
State is set to false on error or shutdown

**Versions:**  
 - Adapter version: 0.0.33

**Comment by TA2k** [comment]
fixed in the github version please retest

**Comment by tillsteinbach** [comment]
Works perfect! Thanks for fixing it!
