### ISSUE TITLE
Support for Skoda, Seat and Cupra Wallboxes (iV Charger, Seat Charger, Cupra Charger)

### ISSUE THREAD

**Issue by Backes89** [TA2k/ioBroker.vw-connect#86]
Problem: 
Due to the fact that Skoda is just releasing the first ENYAQs to the road and a lot of peolpe use the corresponding iV Charger from Skoda (which is simply a rebranded Elli-wallbox like the ID Charger, Seat charger oder cupra charger) it would be a good fit to get the charges from the wallbox itself. The Skoda powerpass app (and every other app which use Elli boxes) have a summary of alle charges. Some people, like me, need to report every month the charged load to the employer.

Solution:
Direct integration with all chargers from the Elli-Network (Elli ist eine Marke des/is a trademark of the Volkswagen Konzerns.) into IO Broker. Like already done with weCharge. Skoda's name for this is "powerpass".

**Comment by TA2k** [comment]
Send me account information via forum and i will integrate this
https://forum.iobroker.net/user/tombox

**Comment by kaiwoknaj** [comment]
How can i add my cupra charger pro?

**Comment by TA2k** [comment]
Write me a message in the iobroker froum

**Comment by Backes89** [comment]
So, I dug myself into the APKs from VWConnectID with integrated WeCharge, the Powerpass-app and the unbranded Elli Charging App.

First impressions... What a mess. Well, VW uses the charger capabilites through their WeConnectID app and they use their own backend which points to "https://wecharge.apps.emea.vwapps.io/ ..."
At Skoda this is divided into the "MySkoda" app and the "Powerpass" app. The Powerpass app uses the Elli backend.

The WeConnectID app delivers all apikeys/backend destinations in a handy config-file which is everything you need to use their backend. This is already implemented with the "wecharge" option in ioBroker.

Skoda (and I would suggest Seat and Cupra as well) use the Elli-backend and they don't have a handy config file with all the infos. I found some apikeys at searching the java-code, but not really any straight endpoint definitions where the call needs to go. At that point I'm at this moment. If anyone else has some suggestions, contact me here in this issue.

@TA2k: I already posted in your thread at the ioBroker-forum. Maybe, if you have any idea, you can contact me there in german.

**Comment by TA2k** [comment]
seat cupra wallboxes are now supported
