### ISSUE TITLE
npm ERR! code ENOTEMPTY

### ISSUE THREAD

**Issue by heckmic** [TA2k/ioBroker.vw-connect#88]
When i try to install the Adapter i get:

npm ERR! syscall rename
npm ERR! path /opt/iobroker/node_modules/abab
npm ERR! dest /opt/iobroker/node_modules/.abab-bvmibCm3
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/abab' -> '/opt/iobroker/node_modules/.abab-bvmibCm3'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-04-23T13_07_33_158Z-debug.log

npm 7.11.0
node v14.16.0

**Comment by TA2k** [comment]
please do not use npm 7 it is not compatible with iobroker
