### ISSUE TITLE
Support for Skoda Enyaq?

### ISSUE THREAD

**Issue by aslten** [TA2k/ioBroker.vw-connect#98]
Just got my Skoda Enyaq and tried to configure the adapter to connect with it. Login works fine but Get vehicles fails with the error that no vehicles are found. I have the MySkoda app working ok with a connection to the car. I am new to the IoBroker platform so it may be that I have got some configuration wrong. I selected Skoda as vehicle type. 

Does the adapter currently support Enyaq? If not this issue should be changed into a feature request. 

If needed I can help out with testing on my car. 

See attached log file

[logfile.txt](https://github.com/TA2k/ioBroker.vw-connect/files/6411680/logfile.txt)

**Comment by TA2k** [comment]
Please contact me via iobroker forum
https://forum.iobroker.net/user/tombox

**Comment by andig** [comment]
Same problem here. The vehicles are not listed in `/fs-car/usermanagement/users/v1/VW/CZ/vehicles`

**Comment by andig** [comment]
I've just tried configuring the Enyaq as ID in https://github.com/andig/evcc which seems to work. Can you confirm?

**Comment by aslten** [comment]
I had a look at https://github.com/lendy007/skodaconnect. Seems to work for getting status.
It seems that vehicles can be listed using https://api.connect.skoda-auto.cz/api/v2/garage/vehicles
Status is returned by https://api.connect.skoda-auto.cz/api/v1/charging/<VIN>/status
Real car data https://customer-profile.apps.emea.vwapps.io/v2/customers/<userId>/realCarData
Still needs to find endpoint for getting status of climatisation and how to control charging and climatisation.

**Comment by andig** [comment]
I've not dug in in detail yet, but it seems to use the normal VW login flow and then the Skoda "native" api. When I try that to retrieve the vehicles I get:

    GET /api/v2/garage/vehicles HTTP/1.1
    Host: api.connect.skoda-auto.cz
    Accept: application/json
    Authorization: Bearer ey...

    HTTP/2.0 401 Unauthorized

    {"error":"invalid_token","error_description":"Invalid JOSE Header kid (MBB01)"}

Couldn't figure out yet what the difference in the login flow is apart from other client/x-client id?

**Comment by heckmic** [comment]
Ok, so what do i have to do to get the Enyaq working?

**Comment by andig** [comment]
It has a unique login flow, see https://github.com/TA2k/ioBroker.vw-connect/issues/98#issuecomment-841791870

**Comment by heckmic** [comment]
Any News?

**Comment by TA2k** [comment]
If you provide me login data I can add this

**Comment by heckmic** [comment]
> If you provide me login data I can add this

Ok, contact me (german) via info@michael-heck.net

**Comment by TA2k** [comment]
On github you can install a version which supports Skoda Enyaq please install and test the new version.
Please test the objects under settings and remote if changing is working properly

**Comment by TA2k** [comment]
add in 0.0.36
